# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Gui_for_main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(703, 709)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.Use_DHCP = QtWidgets.QCheckBox(self.tab)
        self.Use_DHCP.setObjectName("Use_DHCP")
        self.verticalLayout.addWidget(self.Use_DHCP)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setMinimumSize(QtCore.QSize(81, 28))
        self.label_2.setMaximumSize(QtCore.QSize(81, 28))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.IP_address_WAN = QtWidgets.QLineEdit(self.tab)
        self.IP_address_WAN.setObjectName("IP_address_WAN")
        self.horizontalLayout.addWidget(self.IP_address_WAN)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setMinimumSize(QtCore.QSize(81, 27))
        self.label_3.setMaximumSize(QtCore.QSize(81, 27))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.Netmask = QtWidgets.QLineEdit(self.tab)
        self.Netmask.setObjectName("Netmask")
        self.horizontalLayout_2.addWidget(self.Netmask)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setMinimumSize(QtCore.QSize(81, 28))
        self.label_4.setMaximumSize(QtCore.QSize(81, 28))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.Default_Gateway = QtWidgets.QLineEdit(self.tab)
        self.Default_Gateway.setObjectName("Default_Gateway")
        self.horizontalLayout_3.addWidget(self.Default_Gateway)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setMinimumSize(QtCore.QSize(81, 28))
        self.label_5.setMaximumSize(QtCore.QSize(81, 28))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.Hostname = QtWidgets.QLineEdit(self.tab)
        self.Hostname.setObjectName("Hostname")
        self.horizontalLayout_4.addWidget(self.Hostname)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setMinimumSize(QtCore.QSize(81, 28))
        self.label_6.setMaximumSize(QtCore.QSize(81, 28))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.Domain = QtWidgets.QLineEdit(self.tab)
        self.Domain.setObjectName("Domain")
        self.horizontalLayout_5.addWidget(self.Domain)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setMinimumSize(QtCore.QSize(81, 27))
        self.label_7.setMaximumSize(QtCore.QSize(81, 27))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.DNS = QtWidgets.QLineEdit(self.tab)
        self.DNS.setObjectName("DNS")
        self.horizontalLayout_6.addWidget(self.DNS)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setMinimumSize(QtCore.QSize(81, 28))
        self.label_8.setMaximumSize(QtCore.QSize(81, 28))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.SSI = QtWidgets.QComboBox(self.tab)
        self.SSI.setObjectName("SSI")
        self.SSI.addItem("")
        self.SSI.addItem("")
        self.horizontalLayout_7.addWidget(self.SSI)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setMinimumSize(QtCore.QSize(81, 28))
        self.label_10.setMaximumSize(QtCore.QSize(81, 28))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_8.addWidget(self.label_10)
        self.IP_address_SMTP = QtWidgets.QLineEdit(self.tab)
        self.IP_address_SMTP.setObjectName("IP_address_SMTP")
        self.horizontalLayout_8.addWidget(self.IP_address_SMTP)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setMinimumSize(QtCore.QSize(81, 27))
        self.label_11.setMaximumSize(QtCore.QSize(81, 27))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_9.addWidget(self.label_11)
        self.Port = QtWidgets.QLineEdit(self.tab)
        self.Port.setObjectName("Port")
        self.horizontalLayout_9.addWidget(self.Port)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setMinimumSize(QtCore.QSize(81, 28))
        self.label_12.setMaximumSize(QtCore.QSize(81, 28))
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_10.addWidget(self.label_12)
        self.Source = QtWidgets.QLineEdit(self.tab)
        self.Source.setObjectName("Source")
        self.horizontalLayout_10.addWidget(self.Source)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_17.setObjectName("label_17")
        self.verticalLayout_4.addWidget(self.label_17)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_18 = QtWidgets.QLabel(self.tab)
        self.label_18.setMinimumSize(QtCore.QSize(91, 28))
        self.label_18.setMaximumSize(QtCore.QSize(91, 28))
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_14.addWidget(self.label_18)
        self.Old_password = QtWidgets.QLineEdit(self.tab)
        self.Old_password.setObjectName("Old_password")
        self.horizontalLayout_14.addWidget(self.Old_password)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_19 = QtWidgets.QLabel(self.tab)
        self.label_19.setMinimumSize(QtCore.QSize(91, 27))
        self.label_19.setMaximumSize(QtCore.QSize(91, 27))
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_15.addWidget(self.label_19)
        self.New_password = QtWidgets.QLineEdit(self.tab)
        self.New_password.setObjectName("New_password")
        self.horizontalLayout_15.addWidget(self.New_password)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_20 = QtWidgets.QLabel(self.tab)
        self.label_20.setMinimumSize(QtCore.QSize(91, 28))
        self.label_20.setMaximumSize(QtCore.QSize(91, 28))
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_16.addWidget(self.label_20)
        self.Confirm_password = QtWidgets.QLineEdit(self.tab)
        self.Confirm_password.setObjectName("Confirm_password")
        self.horizontalLayout_16.addWidget(self.Confirm_password)
        self.verticalLayout_4.addLayout(self.horizontalLayout_16)
        self.gridLayout.addLayout(self.verticalLayout_4, 1, 1, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.Use_NTP = QtWidgets.QCheckBox(self.tab)
        self.Use_NTP.setChecked(True)
        self.Use_NTP.setObjectName("Use_NTP")
        self.verticalLayout_6.addWidget(self.Use_NTP)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_26 = QtWidgets.QLabel(self.tab)
        self.label_26.setMinimumSize(QtCore.QSize(61, 28))
        self.label_26.setMaximumSize(QtCore.QSize(61, 28))
        self.label_26.setObjectName("label_26")
        self.verticalLayout_8.addWidget(self.label_26)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem)
        self.horizontalLayout_28.addLayout(self.verticalLayout_8)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.NTP_server = QtWidgets.QTextBrowser(self.tab)
        self.NTP_server.setMinimumSize(QtCore.QSize(111, 61))
        self.NTP_server.setObjectName("NTP_server")
        self.verticalLayout_7.addWidget(self.NTP_server)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.Add_string = QtWidgets.QLineEdit(self.tab)
        self.Add_string.setObjectName("Add_string")
        self.horizontalLayout_27.addWidget(self.Add_string)
        self.Add_btn = QtWidgets.QPushButton(self.tab)
        self.Add_btn.setMinimumSize(QtCore.QSize(31, 23))
        self.Add_btn.setMaximumSize(QtCore.QSize(31, 23))
        self.Add_btn.setObjectName("Add_btn")
        self.horizontalLayout_27.addWidget(self.Add_btn)
        self.Del_btn = QtWidgets.QPushButton(self.tab)
        self.Del_btn.setMinimumSize(QtCore.QSize(31, 23))
        self.Del_btn.setMaximumSize(QtCore.QSize(31, 23))
        self.Del_btn.setObjectName("Del_btn")
        self.horizontalLayout_27.addWidget(self.Del_btn)
        self.verticalLayout_7.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28.addLayout(self.verticalLayout_7)
        self.verticalLayout_6.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_27 = QtWidgets.QLabel(self.tab)
        self.label_27.setMinimumSize(QtCore.QSize(81, 27))
        self.label_27.setMaximumSize(QtCore.QSize(81, 27))
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_21.addWidget(self.label_27)
        self.TimeZone = QtWidgets.QComboBox(self.tab)
        self.TimeZone.setEnabled(True)
        self.TimeZone.setObjectName("TimeZone")
        self.TimeZone.addItem("")
        self.TimeZone.addItem("")
        self.TimeZone.addItem("")
        self.TimeZone.addItem("")
        self.TimeZone.addItem("")
        self.TimeZone.addItem("")
        self.TimeZone.addItem("")
        self.TimeZone.addItem("")
        self.TimeZone.addItem("")
        self.TimeZone.addItem("")
        self.TimeZone.addItem("")
        self.horizontalLayout_21.addWidget(self.TimeZone)
        self.verticalLayout_6.addLayout(self.horizontalLayout_21)
        self.label_25 = QtWidgets.QLabel(self.tab)
        self.label_25.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_25.setObjectName("label_25")
        self.verticalLayout_6.addWidget(self.label_25)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_28 = QtWidgets.QLabel(self.tab)
        self.label_28.setMinimumSize(QtCore.QSize(101, 28))
        self.label_28.setMaximumSize(QtCore.QSize(101, 28))
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_22.addWidget(self.label_28)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.Date_dd = QtWidgets.QSpinBox(self.tab)
        self.Date_dd.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.Date_dd.setMaximum(31)
        self.Date_dd.setObjectName("Date_dd")
        self.horizontalLayout_20.addWidget(self.Date_dd)
        self.label_33 = QtWidgets.QLabel(self.tab)
        self.label_33.setMinimumSize(QtCore.QSize(16, 16))
        self.label_33.setMaximumSize(QtCore.QSize(16, 16))
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_20.addWidget(self.label_33)
        self.Date_mm = QtWidgets.QSpinBox(self.tab)
        self.Date_mm.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.Date_mm.setMaximum(12)
        self.Date_mm.setObjectName("Date_mm")
        self.horizontalLayout_20.addWidget(self.Date_mm)
        self.label_35 = QtWidgets.QLabel(self.tab)
        self.label_35.setMinimumSize(QtCore.QSize(16, 16))
        self.label_35.setMaximumSize(QtCore.QSize(16, 16))
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_20.addWidget(self.label_35)
        self.Date_yyyy = QtWidgets.QSpinBox(self.tab)
        self.Date_yyyy.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.Date_yyyy.setMaximum(9999)
        self.Date_yyyy.setObjectName("Date_yyyy")
        self.horizontalLayout_20.addWidget(self.Date_yyyy)
        self.horizontalLayout_22.addLayout(self.horizontalLayout_20)
        self.verticalLayout_6.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_29 = QtWidgets.QLabel(self.tab)
        self.label_29.setMinimumSize(QtCore.QSize(81, 28))
        self.label_29.setMaximumSize(QtCore.QSize(81, 28))
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_23.addWidget(self.label_29)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.Time_hh = QtWidgets.QSpinBox(self.tab)
        self.Time_hh.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.Time_hh.setMaximum(23)
        self.Time_hh.setObjectName("Time_hh")
        self.horizontalLayout_30.addWidget(self.Time_hh)
        self.label_34 = QtWidgets.QLabel(self.tab)
        self.label_34.setMinimumSize(QtCore.QSize(16, 16))
        self.label_34.setMaximumSize(QtCore.QSize(16, 16))
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_30.addWidget(self.label_34)
        self.Time_mm = QtWidgets.QSpinBox(self.tab)
        self.Time_mm.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.Time_mm.setMaximum(59)
        self.Time_mm.setProperty("value", 0)
        self.Time_mm.setObjectName("Time_mm")
        self.horizontalLayout_30.addWidget(self.Time_mm)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem1)
        self.horizontalLayout_23.addLayout(self.horizontalLayout_30)
        self.verticalLayout_6.addLayout(self.horizontalLayout_23)
        self.gridLayout.addLayout(self.verticalLayout_6, 0, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_13.setObjectName("label_13")
        self.verticalLayout_3.addWidget(self.label_13)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setMinimumSize(QtCore.QSize(81, 28))
        self.label_14.setMaximumSize(QtCore.QSize(81, 28))
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_11.addWidget(self.label_14)
        self.Name_SIP = QtWidgets.QLineEdit(self.tab)
        self.Name_SIP.setObjectName("Name_SIP")
        self.horizontalLayout_11.addWidget(self.Name_SIP)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setMinimumSize(QtCore.QSize(81, 27))
        self.label_15.setMaximumSize(QtCore.QSize(81, 27))
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_12.addWidget(self.label_15)
        self.Unicast_port = QtWidgets.QLineEdit(self.tab)
        self.Unicast_port.setObjectName("Unicast_port")
        self.horizontalLayout_12.addWidget(self.Unicast_port)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setMinimumSize(QtCore.QSize(81, 28))
        self.label_16.setMaximumSize(QtCore.QSize(81, 28))
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_13.addWidget(self.label_16)
        self.Multicast_port_SMTP = QtWidgets.QLineEdit(self.tab)
        self.Multicast_port_SMTP.setObjectName("Multicast_port_SMTP")
        self.horizontalLayout_13.addWidget(self.Multicast_port_SMTP)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.gridLayout.addLayout(self.verticalLayout_3, 2, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_21 = QtWidgets.QLabel(self.tab)
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_21.setObjectName("label_21")
        self.verticalLayout_5.addWidget(self.label_21)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_22 = QtWidgets.QLabel(self.tab)
        self.label_22.setMinimumSize(QtCore.QSize(81, 28))
        self.label_22.setMaximumSize(QtCore.QSize(81, 28))
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_17.addWidget(self.label_22)
        self.Name_gatekeeper = QtWidgets.QLineEdit(self.tab)
        self.Name_gatekeeper.setObjectName("Name_gatekeeper")
        self.horizontalLayout_17.addWidget(self.Name_gatekeeper)
        self.verticalLayout_5.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_23 = QtWidgets.QLabel(self.tab)
        self.label_23.setMinimumSize(QtCore.QSize(81, 27))
        self.label_23.setMaximumSize(QtCore.QSize(81, 27))
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_18.addWidget(self.label_23)
        self.Unicast = QtWidgets.QLineEdit(self.tab)
        self.Unicast.setObjectName("Unicast")
        self.horizontalLayout_18.addWidget(self.Unicast)
        self.verticalLayout_5.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_24 = QtWidgets.QLabel(self.tab)
        self.label_24.setMinimumSize(QtCore.QSize(81, 28))
        self.label_24.setMaximumSize(QtCore.QSize(81, 28))
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_19.addWidget(self.label_24)
        self.Multicast_port_gatekeeper = QtWidgets.QLineEdit(self.tab)
        self.Multicast_port_gatekeeper.setObjectName("Multicast_port_gatekeeper")
        self.horizontalLayout_19.addWidget(self.Multicast_port_gatekeeper)
        self.verticalLayout_5.addLayout(self.horizontalLayout_19)
        self.gridLayout.addLayout(self.verticalLayout_5, 2, 1, 1, 1)
        self.horizontalLayout_24.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.Users_edit_btn = QtWidgets.QPushButton(self.tab_2)
        self.Users_edit_btn.setMinimumSize(QtCore.QSize(91, 23))
        self.Users_edit_btn.setMaximumSize(QtCore.QSize(91, 23))
        self.Users_edit_btn.setObjectName("Users_edit_btn")
        self.horizontalLayout_29.addWidget(self.Users_edit_btn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem2)
        self.Action_options = QtWidgets.QGroupBox(self.tab_2)
        self.Action_options.setObjectName("Action_options")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.Action_options)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.Del_Radio = QtWidgets.QRadioButton(self.Action_options)
        self.Del_Radio.setObjectName("Del_Radio")
        self.horizontalLayout_31.addWidget(self.Del_Radio)
        self.Edit_Radio = QtWidgets.QRadioButton(self.Action_options)
        self.Edit_Radio.setChecked(True)
        self.Edit_Radio.setObjectName("Edit_Radio")
        self.horizontalLayout_31.addWidget(self.Edit_Radio)
        self.horizontalLayout_29.addWidget(self.Action_options)
        self.verticalLayout_9.addLayout(self.horizontalLayout_29)
        self.Users_table = QtWidgets.QTableWidget(self.tab_2)
        self.Users_table.setObjectName("Users_table")
        self.Users_table.setColumnCount(6)
        self.Users_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Users_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Users_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Users_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Users_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Users_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Users_table.setHorizontalHeaderItem(5, item)
        self.verticalLayout_9.addWidget(self.Users_table)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.Gateways_Add_btn = QtWidgets.QPushButton(self.tab_3)
        self.Gateways_Add_btn.setMinimumSize(QtCore.QSize(91, 23))
        self.Gateways_Add_btn.setMaximumSize(QtCore.QSize(91, 23))
        self.Gateways_Add_btn.setObjectName("Gateways_Add_btn")
        self.horizontalLayout_32.addWidget(self.Gateways_Add_btn)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem3)
        self.Action_options_2 = QtWidgets.QGroupBox(self.tab_3)
        self.Action_options_2.setObjectName("Action_options_2")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.Action_options_2)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.Del_Radio_2 = QtWidgets.QRadioButton(self.Action_options_2)
        self.Del_Radio_2.setObjectName("Del_Radio_2")
        self.horizontalLayout_33.addWidget(self.Del_Radio_2)
        self.Edit_Radio_2 = QtWidgets.QRadioButton(self.Action_options_2)
        self.Edit_Radio_2.setChecked(True)
        self.Edit_Radio_2.setObjectName("Edit_Radio_2")
        self.horizontalLayout_33.addWidget(self.Edit_Radio_2)
        self.horizontalLayout_32.addWidget(self.Action_options_2)
        self.verticalLayout_11.addLayout(self.horizontalLayout_32)
        self.Gateways_table = QtWidgets.QTableWidget(self.tab_3)
        self.Gateways_table.setObjectName("Gateways_table")
        self.Gateways_table.setColumnCount(4)
        self.Gateways_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Gateways_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Gateways_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Gateways_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Gateways_table.setHorizontalHeaderItem(3, item)
        self.verticalLayout_11.addWidget(self.Gateways_table)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.Services_Add_btn = QtWidgets.QPushButton(self.tab_4)
        self.Services_Add_btn.setMinimumSize(QtCore.QSize(91, 23))
        self.Services_Add_btn.setMaximumSize(QtCore.QSize(91, 23))
        self.Services_Add_btn.setObjectName("Services_Add_btn")
        self.horizontalLayout_34.addWidget(self.Services_Add_btn)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem4)
        self.Action_options_3 = QtWidgets.QGroupBox(self.tab_4)
        self.Action_options_3.setObjectName("Action_options_3")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout(self.Action_options_3)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.Del_Radio_3 = QtWidgets.QRadioButton(self.Action_options_3)
        self.Del_Radio_3.setObjectName("Del_Radio_3")
        self.horizontalLayout_35.addWidget(self.Del_Radio_3)
        self.Edit_Radio_3 = QtWidgets.QRadioButton(self.Action_options_3)
        self.Edit_Radio_3.setChecked(True)
        self.Edit_Radio_3.setObjectName("Edit_Radio_3")
        self.horizontalLayout_35.addWidget(self.Edit_Radio_3)
        self.horizontalLayout_34.addWidget(self.Action_options_3)
        self.verticalLayout_12.addLayout(self.horizontalLayout_34)
        self.Services_Table = QtWidgets.QTableWidget(self.tab_4)
        self.Services_Table.setObjectName("Services_Table")
        self.Services_Table.setColumnCount(4)
        self.Services_Table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Services_Table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Services_Table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Services_Table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Services_Table.setHorizontalHeaderItem(3, item)
        self.verticalLayout_12.addWidget(self.Services_Table)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.Routes_Add_btn = QtWidgets.QPushButton(self.tab_5)
        self.Routes_Add_btn.setMinimumSize(QtCore.QSize(91, 23))
        self.Routes_Add_btn.setMaximumSize(QtCore.QSize(91, 23))
        self.Routes_Add_btn.setObjectName("Routes_Add_btn")
        self.horizontalLayout_36.addWidget(self.Routes_Add_btn)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_36.addItem(spacerItem5)
        self.Action_options_4 = QtWidgets.QGroupBox(self.tab_5)
        self.Action_options_4.setObjectName("Action_options_4")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout(self.Action_options_4)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.Del_Radio_4 = QtWidgets.QRadioButton(self.Action_options_4)
        self.Del_Radio_4.setObjectName("Del_Radio_4")
        self.horizontalLayout_37.addWidget(self.Del_Radio_4)
        self.Edit_Radio_4 = QtWidgets.QRadioButton(self.Action_options_4)
        self.Edit_Radio_4.setChecked(True)
        self.Edit_Radio_4.setObjectName("Edit_Radio_4")
        self.horizontalLayout_37.addWidget(self.Edit_Radio_4)
        self.horizontalLayout_36.addWidget(self.Action_options_4)
        self.verticalLayout_13.addLayout(self.horizontalLayout_36)
        self.Routes_Table = QtWidgets.QTableWidget(self.tab_5)
        self.Routes_Table.setObjectName("Routes_Table")
        self.Routes_Table.setColumnCount(9)
        self.Routes_Table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Routes_Table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Routes_Table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Routes_Table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Routes_Table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Routes_Table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Routes_Table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Routes_Table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.Routes_Table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.Routes_Table.setHorizontalHeaderItem(8, item)
        self.verticalLayout_13.addWidget(self.Routes_Table)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.Groups_Add_btn = QtWidgets.QPushButton(self.tab_6)
        self.Groups_Add_btn.setMinimumSize(QtCore.QSize(91, 23))
        self.Groups_Add_btn.setMaximumSize(QtCore.QSize(91, 23))
        self.Groups_Add_btn.setObjectName("Groups_Add_btn")
        self.horizontalLayout_39.addWidget(self.Groups_Add_btn)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_39.addItem(spacerItem6)
        self.Action_options_5 = QtWidgets.QGroupBox(self.tab_6)
        self.Action_options_5.setObjectName("Action_options_5")
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout(self.Action_options_5)
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.Del_Radio_5 = QtWidgets.QRadioButton(self.Action_options_5)
        self.Del_Radio_5.setObjectName("Del_Radio_5")
        self.horizontalLayout_40.addWidget(self.Del_Radio_5)
        self.Edit_Radio_5 = QtWidgets.QRadioButton(self.Action_options_5)
        self.Edit_Radio_5.setChecked(True)
        self.Edit_Radio_5.setObjectName("Edit_Radio_5")
        self.horizontalLayout_40.addWidget(self.Edit_Radio_5)
        self.horizontalLayout_39.addWidget(self.Action_options_5)
        self.verticalLayout_14.addLayout(self.horizontalLayout_39)
        self.Groups_Table = QtWidgets.QTableWidget(self.tab_6)
        self.Groups_Table.setObjectName("Groups_Table")
        self.Groups_Table.setColumnCount(8)
        self.Groups_Table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Groups_Table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Groups_Table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Groups_Table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Groups_Table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Groups_Table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Groups_Table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Groups_Table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.Groups_Table.setHorizontalHeaderItem(7, item)
        self.verticalLayout_14.addWidget(self.Groups_Table)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.tab_7)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_36 = QtWidgets.QLabel(self.tab_7)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_15.addWidget(self.label_36)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.Pro_Upload_prompt = QtWidgets.QLineEdit(self.tab_7)
        self.Pro_Upload_prompt.setMinimumSize(QtCore.QSize(121, 20))
        self.Pro_Upload_prompt.setObjectName("Pro_Upload_prompt")
        self.horizontalLayout_26.addWidget(self.Pro_Upload_prompt)
        self.Pro_Choose_path_btn = QtWidgets.QPushButton(self.tab_7)
        self.Pro_Choose_path_btn.setMaximumSize(QtCore.QSize(101, 23))
        self.Pro_Choose_path_btn.setObjectName("Pro_Choose_path_btn")
        self.horizontalLayout_26.addWidget(self.Pro_Choose_path_btn)
        self.verticalLayout_15.addLayout(self.horizontalLayout_26)
        self.label_31 = QtWidgets.QLabel(self.tab_7)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_15.addWidget(self.label_31)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.Pro_Name = QtWidgets.QLineEdit(self.tab_7)
        self.Pro_Name.setMinimumSize(QtCore.QSize(121, 20))
        self.Pro_Name.setMaximumSize(QtCore.QSize(122, 20))
        self.Pro_Name.setObjectName("Pro_Name")
        self.horizontalLayout_25.addWidget(self.Pro_Name)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem7)
        self.verticalLayout_15.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.Pro_Upload_btn = QtWidgets.QPushButton(self.tab_7)
        self.Pro_Upload_btn.setObjectName("Pro_Upload_btn")
        self.horizontalLayout_41.addWidget(self.Pro_Upload_btn)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_41.addItem(spacerItem8)
        self.Action_options_6 = QtWidgets.QGroupBox(self.tab_7)
        self.Action_options_6.setObjectName("Action_options_6")
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout(self.Action_options_6)
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.Del_Radio_6 = QtWidgets.QRadioButton(self.Action_options_6)
        self.Del_Radio_6.setObjectName("Del_Radio_6")
        self.horizontalLayout_42.addWidget(self.Del_Radio_6)
        self.Edit_Radio_6 = QtWidgets.QRadioButton(self.Action_options_6)
        self.Edit_Radio_6.setChecked(True)
        self.Edit_Radio_6.setObjectName("Edit_Radio_6")
        self.horizontalLayout_42.addWidget(self.Edit_Radio_6)
        self.horizontalLayout_41.addWidget(self.Action_options_6)
        self.verticalLayout_15.addLayout(self.horizontalLayout_41)
        self.label_30 = QtWidgets.QLabel(self.tab_7)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_15.addWidget(self.label_30)
        self.Prompts_Table = QtWidgets.QTableWidget(self.tab_7)
        self.Prompts_Table.setObjectName("Prompts_Table")
        self.Prompts_Table.setColumnCount(2)
        self.Prompts_Table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Prompts_Table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Prompts_Table.setHorizontalHeaderItem(1, item)
        self.verticalLayout_15.addWidget(self.Prompts_Table)
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout(self.tab_8)
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.Rad_Ecb = QtWidgets.QCheckBox(self.tab_8)
        self.Rad_Ecb.setObjectName("Rad_Ecb")
        self.verticalLayout_16.addWidget(self.Rad_Ecb)
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_43 = QtWidgets.QLabel(self.tab_8)
        self.label_43.setMinimumSize(QtCore.QSize(131, 16))
        self.label_43.setMaximumSize(QtCore.QSize(131, 16))
        self.label_43.setObjectName("label_43")
        self.verticalLayout_17.addWidget(self.label_43)
        self.label_42 = QtWidgets.QLabel(self.tab_8)
        self.label_42.setMinimumSize(QtCore.QSize(131, 16))
        self.label_42.setMaximumSize(QtCore.QSize(131, 16))
        self.label_42.setObjectName("label_42")
        self.verticalLayout_17.addWidget(self.label_42)
        self.label_41 = QtWidgets.QLabel(self.tab_8)
        self.label_41.setMinimumSize(QtCore.QSize(131, 16))
        self.label_41.setMaximumSize(QtCore.QSize(131, 16))
        self.label_41.setObjectName("label_41")
        self.verticalLayout_17.addWidget(self.label_41)
        self.label_40 = QtWidgets.QLabel(self.tab_8)
        self.label_40.setMinimumSize(QtCore.QSize(131, 16))
        self.label_40.setMaximumSize(QtCore.QSize(131, 16))
        self.label_40.setObjectName("label_40")
        self.verticalLayout_17.addWidget(self.label_40)
        self.label_39 = QtWidgets.QLabel(self.tab_8)
        self.label_39.setMinimumSize(QtCore.QSize(131, 16))
        self.label_39.setMaximumSize(QtCore.QSize(131, 16))
        self.label_39.setObjectName("label_39")
        self.verticalLayout_17.addWidget(self.label_39)
        self.label_38 = QtWidgets.QLabel(self.tab_8)
        self.label_38.setMinimumSize(QtCore.QSize(131, 16))
        self.label_38.setMaximumSize(QtCore.QSize(131, 16))
        self.label_38.setObjectName("label_38")
        self.verticalLayout_17.addWidget(self.label_38)
        self.label_37 = QtWidgets.QLabel(self.tab_8)
        self.label_37.setMinimumSize(QtCore.QSize(131, 16))
        self.label_37.setMaximumSize(QtCore.QSize(131, 16))
        self.label_37.setObjectName("label_37")
        self.verticalLayout_17.addWidget(self.label_37)
        self.label_32 = QtWidgets.QLabel(self.tab_8)
        self.label_32.setMinimumSize(QtCore.QSize(131, 16))
        self.label_32.setMaximumSize(QtCore.QSize(131, 16))
        self.label_32.setObjectName("label_32")
        self.verticalLayout_17.addWidget(self.label_32)
        self.horizontalLayout_43.addLayout(self.verticalLayout_17)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.Rad_Secret = QtWidgets.QLineEdit(self.tab_8)
        self.Rad_Secret.setMinimumSize(QtCore.QSize(113, 20))
        self.Rad_Secret.setMaximumSize(QtCore.QSize(113, 20))
        self.Rad_Secret.setObjectName("Rad_Secret")
        self.verticalLayout_18.addWidget(self.Rad_Secret)
        self.Reg_Retransmission_count = QtWidgets.QLineEdit(self.tab_8)
        self.Reg_Retransmission_count.setMinimumSize(QtCore.QSize(113, 20))
        self.Reg_Retransmission_count.setMaximumSize(QtCore.QSize(113, 20))
        self.Reg_Retransmission_count.setObjectName("Reg_Retransmission_count")
        self.verticalLayout_18.addWidget(self.Reg_Retransmission_count)
        self.Rad_Retransmission_interval = QtWidgets.QLineEdit(self.tab_8)
        self.Rad_Retransmission_interval.setMinimumSize(QtCore.QSize(113, 20))
        self.Rad_Retransmission_interval.setMaximumSize(QtCore.QSize(113, 20))
        self.Rad_Retransmission_interval.setObjectName("Rad_Retransmission_interval")
        self.verticalLayout_18.addWidget(self.Rad_Retransmission_interval)
        self.Rad_Interim_msg_send_interval = QtWidgets.QLineEdit(self.tab_8)
        self.Rad_Interim_msg_send_interval.setMinimumSize(QtCore.QSize(113, 20))
        self.Rad_Interim_msg_send_interval.setMaximumSize(QtCore.QSize(113, 20))
        self.Rad_Interim_msg_send_interval.setObjectName("Rad_Interim_msg_send_interval")
        self.verticalLayout_18.addWidget(self.Rad_Interim_msg_send_interval)
        self.Rad_Max_call_time = QtWidgets.QLineEdit(self.tab_8)
        self.Rad_Max_call_time.setMinimumSize(QtCore.QSize(113, 20))
        self.Rad_Max_call_time.setMaximumSize(QtCore.QSize(113, 20))
        self.Rad_Max_call_time.setObjectName("Rad_Max_call_time")
        self.verticalLayout_18.addWidget(self.Rad_Max_call_time)
        self.Rad_Service_type = QtWidgets.QLineEdit(self.tab_8)
        self.Rad_Service_type.setMinimumSize(QtCore.QSize(113, 20))
        self.Rad_Service_type.setMaximumSize(QtCore.QSize(113, 20))
        self.Rad_Service_type.setObjectName("Rad_Service_type")
        self.verticalLayout_18.addWidget(self.Rad_Service_type)
        self.Rad_Framed_protocol = QtWidgets.QLineEdit(self.tab_8)
        self.Rad_Framed_protocol.setMinimumSize(QtCore.QSize(113, 20))
        self.Rad_Framed_protocol.setMaximumSize(QtCore.QSize(113, 20))
        self.Rad_Framed_protocol.setObjectName("Rad_Framed_protocol")
        self.verticalLayout_18.addWidget(self.Rad_Framed_protocol)
        self.Rad_Nas_IP = QtWidgets.QLineEdit(self.tab_8)
        self.Rad_Nas_IP.setMinimumSize(QtCore.QSize(113, 20))
        self.Rad_Nas_IP.setMaximumSize(QtCore.QSize(113, 20))
        self.Rad_Nas_IP.setObjectName("Rad_Nas_IP")
        self.verticalLayout_18.addWidget(self.Rad_Nas_IP)
        self.horizontalLayout_43.addLayout(self.verticalLayout_18)
        self.verticalLayout_16.addLayout(self.horizontalLayout_43)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.Rad_Disc = QtWidgets.QCheckBox(self.tab_8)
        self.Rad_Disc.setObjectName("Rad_Disc")
        self.verticalLayout_19.addWidget(self.Rad_Disc)
        self.Rad_Auth_reg = QtWidgets.QCheckBox(self.tab_8)
        self.Rad_Auth_reg.setObjectName("Rad_Auth_reg")
        self.verticalLayout_19.addWidget(self.Rad_Auth_reg)
        self.Rad_Auth_call = QtWidgets.QCheckBox(self.tab_8)
        self.Rad_Auth_call.setObjectName("Rad_Auth_call")
        self.verticalLayout_19.addWidget(self.Rad_Auth_call)
        self.Rad_send_boot = QtWidgets.QCheckBox(self.tab_8)
        self.Rad_send_boot.setObjectName("Rad_send_boot")
        self.verticalLayout_19.addWidget(self.Rad_send_boot)
        self.Rad_Send_accounting = QtWidgets.QCheckBox(self.tab_8)
        self.Rad_Send_accounting.setObjectName("Rad_Send_accounting")
        self.verticalLayout_19.addWidget(self.Rad_Send_accounting)
        self.Rad_Send_interim = QtWidgets.QCheckBox(self.tab_8)
        self.Rad_Send_interim.setObjectName("Rad_Send_interim")
        self.verticalLayout_19.addWidget(self.Rad_Send_interim)
        self.Rad_Cisco_comp = QtWidgets.QCheckBox(self.tab_8)
        self.Rad_Cisco_comp.setMinimumSize(QtCore.QSize(211, 17))
        self.Rad_Cisco_comp.setMaximumSize(QtCore.QSize(211, 17))
        self.Rad_Cisco_comp.setObjectName("Rad_Cisco_comp")
        self.verticalLayout_19.addWidget(self.Rad_Cisco_comp)
        self.Rad_Send_called = QtWidgets.QCheckBox(self.tab_8)
        self.Rad_Send_called.setObjectName("Rad_Send_called")
        self.verticalLayout_19.addWidget(self.Rad_Send_called)
        self.verticalLayout_16.addLayout(self.verticalLayout_19)
        self.horizontalLayout_45.addLayout(self.verticalLayout_16)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_44 = QtWidgets.QLabel(self.tab_8)
        self.label_44.setObjectName("label_44")
        self.verticalLayout_20.addWidget(self.label_44)
        self.Rad_Server_auth = QtWidgets.QTextBrowser(self.tab_8)
        self.Rad_Server_auth.setMinimumSize(QtCore.QSize(111, 61))
        self.Rad_Server_auth.setObjectName("Rad_Server_auth")
        self.verticalLayout_20.addWidget(self.Rad_Server_auth)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.Add_string_2 = QtWidgets.QLineEdit(self.tab_8)
        self.Add_string_2.setObjectName("Add_string_2")
        self.horizontalLayout_44.addWidget(self.Add_string_2)
        self.Rad_Add_server_btn = QtWidgets.QPushButton(self.tab_8)
        self.Rad_Add_server_btn.setMinimumSize(QtCore.QSize(31, 23))
        self.Rad_Add_server_btn.setMaximumSize(QtCore.QSize(31, 23))
        self.Rad_Add_server_btn.setObjectName("Rad_Add_server_btn")
        self.horizontalLayout_44.addWidget(self.Rad_Add_server_btn)
        self.Rad_Add_server_btn_2 = QtWidgets.QPushButton(self.tab_8)
        self.Rad_Add_server_btn_2.setMinimumSize(QtCore.QSize(31, 23))
        self.Rad_Add_server_btn_2.setMaximumSize(QtCore.QSize(31, 23))
        self.Rad_Add_server_btn_2.setObjectName("Rad_Add_server_btn_2")
        self.horizontalLayout_44.addWidget(self.Rad_Add_server_btn_2)
        self.verticalLayout_20.addLayout(self.horizontalLayout_44)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_20.addItem(spacerItem9)
        self.horizontalLayout_45.addLayout(self.verticalLayout_20)
        self.tabWidget.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.tab_9)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.Statistics_Table = QtWidgets.QTableWidget(self.tab_9)
        self.Statistics_Table.setObjectName("Statistics_Table")
        self.Statistics_Table.setColumnCount(5)
        self.Statistics_Table.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.Statistics_Table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Statistics_Table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Statistics_Table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Statistics_Table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Statistics_Table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Statistics_Table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Statistics_Table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Statistics_Table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Statistics_Table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Statistics_Table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Statistics_Table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Statistics_Table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Statistics_Table.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Statistics_Table.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Statistics_Table.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Statistics_Table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Statistics_Table.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Statistics_Table.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Statistics_Table.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Statistics_Table.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Statistics_Table.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Statistics_Table.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Statistics_Table.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Statistics_Table.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Statistics_Table.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Statistics_Table.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Statistics_Table.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Statistics_Table.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Statistics_Table.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Statistics_Table.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Statistics_Table.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Statistics_Table.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Statistics_Table.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Statistics_Table.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Statistics_Table.setItem(4, 4, item)
        self.verticalLayout_21.addWidget(self.Statistics_Table)
        self.tabWidget.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.tab_10)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_45 = QtWidgets.QLabel(self.tab_10)
        self.label_45.setMinimumSize(QtCore.QSize(141, 16))
        self.label_45.setMaximumSize(QtCore.QSize(141, 16))
        self.label_45.setObjectName("label_45")
        self.verticalLayout_22.addWidget(self.label_45)
        self.label_46 = QtWidgets.QLabel(self.tab_10)
        self.label_46.setMinimumSize(QtCore.QSize(141, 16))
        self.label_46.setMaximumSize(QtCore.QSize(141, 16))
        self.label_46.setObjectName("label_46")
        self.verticalLayout_22.addWidget(self.label_46)
        self.label_47 = QtWidgets.QLabel(self.tab_10)
        self.label_47.setMinimumSize(QtCore.QSize(141, 16))
        self.label_47.setMaximumSize(QtCore.QSize(141, 16))
        self.label_47.setObjectName("label_47")
        self.verticalLayout_22.addWidget(self.label_47)
        self.label_48 = QtWidgets.QLabel(self.tab_10)
        self.label_48.setMinimumSize(QtCore.QSize(141, 16))
        self.label_48.setMaximumSize(QtCore.QSize(141, 16))
        self.label_48.setObjectName("label_48")
        self.verticalLayout_22.addWidget(self.label_48)
        self.horizontalLayout_46.addLayout(self.verticalLayout_22)
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.Logs_Keep_log = QtWidgets.QLineEdit(self.tab_10)
        self.Logs_Keep_log.setMinimumSize(QtCore.QSize(203, 20))
        self.Logs_Keep_log.setMaximumSize(QtCore.QSize(203, 20))
        self.Logs_Keep_log.setObjectName("Logs_Keep_log")
        self.verticalLayout_23.addWidget(self.Logs_Keep_log)
        self.Logs_Keep_User = QtWidgets.QLineEdit(self.tab_10)
        self.Logs_Keep_User.setMinimumSize(QtCore.QSize(203, 20))
        self.Logs_Keep_User.setMaximumSize(QtCore.QSize(203, 20))
        self.Logs_Keep_User.setObjectName("Logs_Keep_User")
        self.verticalLayout_23.addWidget(self.Logs_Keep_User)
        self.Logs_Keep_Admin = QtWidgets.QLineEdit(self.tab_10)
        self.Logs_Keep_Admin.setMinimumSize(QtCore.QSize(203, 20))
        self.Logs_Keep_Admin.setMaximumSize(QtCore.QSize(203, 20))
        self.Logs_Keep_Admin.setObjectName("Logs_Keep_Admin")
        self.verticalLayout_23.addWidget(self.Logs_Keep_Admin)
        self.Logs_Email_CDB = QtWidgets.QLineEdit(self.tab_10)
        self.Logs_Email_CDB.setMinimumSize(QtCore.QSize(203, 20))
        self.Logs_Email_CDB.setMaximumSize(QtCore.QSize(203, 20))
        self.Logs_Email_CDB.setObjectName("Logs_Email_CDB")
        self.verticalLayout_23.addWidget(self.Logs_Email_CDB)
        self.horizontalLayout_47.addLayout(self.verticalLayout_23)
        self.horizontalLayout_46.addLayout(self.horizontalLayout_47)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_49 = QtWidgets.QLabel(self.tab_10)
        self.label_49.setObjectName("label_49")
        self.verticalLayout_24.addWidget(self.label_49)
        self.label_50 = QtWidgets.QLabel(self.tab_10)
        self.label_50.setObjectName("label_50")
        self.verticalLayout_24.addWidget(self.label_50)
        self.label_51 = QtWidgets.QLabel(self.tab_10)
        self.label_51.setObjectName("label_51")
        self.verticalLayout_24.addWidget(self.label_51)
        self.label_52 = QtWidgets.QLabel(self.tab_10)
        self.label_52.setText("")
        self.label_52.setObjectName("label_52")
        self.verticalLayout_24.addWidget(self.label_52)
        self.horizontalLayout_46.addLayout(self.verticalLayout_24)
        self.verticalLayout_25.addLayout(self.horizontalLayout_46)
        self.Logs_Table = QtWidgets.QTableWidget(self.tab_10)
        self.Logs_Table.setObjectName("Logs_Table")
        self.Logs_Table.setColumnCount(2)
        self.Logs_Table.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.Logs_Table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Logs_Table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Logs_Table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Logs_Table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Logs_Table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Logs_Table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Logs_Table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Logs_Table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Logs_Table.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Logs_Table.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Logs_Table.setItem(2, 1, item)
        self.verticalLayout_25.addWidget(self.Logs_Table)
        self.tabWidget.addTab(self.tab_10, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.tab_11)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.label_53 = QtWidgets.QLabel(self.tab_11)
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_51.addWidget(self.label_53)
        self.Action_options_7 = QtWidgets.QGroupBox(self.tab_11)
        self.Action_options_7.setObjectName("Action_options_7")
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout(self.Action_options_7)
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.Del_Radio_7 = QtWidgets.QRadioButton(self.Action_options_7)
        self.Del_Radio_7.setObjectName("Del_Radio_7")
        self.horizontalLayout_50.addWidget(self.Del_Radio_7)
        self.Edit_Radio_7 = QtWidgets.QRadioButton(self.Action_options_7)
        self.Edit_Radio_7.setChecked(True)
        self.Edit_Radio_7.setObjectName("Edit_Radio_7")
        self.horizontalLayout_50.addWidget(self.Edit_Radio_7)
        self.horizontalLayout_51.addWidget(self.Action_options_7)
        self.verticalLayout_26.addLayout(self.horizontalLayout_51)
        self.Update_Table = QtWidgets.QTableWidget(self.tab_11)
        self.Update_Table.setObjectName("Update_Table")
        self.Update_Table.setColumnCount(4)
        self.Update_Table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Update_Table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Update_Table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Update_Table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Update_Table.setHorizontalHeaderItem(3, item)
        self.verticalLayout_26.addWidget(self.Update_Table)
        self.label_55 = QtWidgets.QLabel(self.tab_11)
        self.label_55.setObjectName("label_55")
        self.verticalLayout_26.addWidget(self.label_55)
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.Update_Name = QtWidgets.QLineEdit(self.tab_11)
        self.Update_Name.setMinimumSize(QtCore.QSize(121, 20))
        self.Update_Name.setMaximumSize(QtCore.QSize(122, 20))
        self.Update_Name.setObjectName("Update_Name")
        self.horizontalLayout_49.addWidget(self.Update_Name)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_49.addItem(spacerItem10)
        self.verticalLayout_26.addLayout(self.horizontalLayout_49)
        self.label_54 = QtWidgets.QLabel(self.tab_11)
        self.label_54.setObjectName("label_54")
        self.verticalLayout_26.addWidget(self.label_54)
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.Update_Upload_prompt = QtWidgets.QLineEdit(self.tab_11)
        self.Update_Upload_prompt.setMinimumSize(QtCore.QSize(121, 20))
        self.Update_Upload_prompt.setObjectName("Update_Upload_prompt")
        self.horizontalLayout_48.addWidget(self.Update_Upload_prompt)
        self.Update_Choose_path_btn = QtWidgets.QPushButton(self.tab_11)
        self.Update_Choose_path_btn.setMaximumSize(QtCore.QSize(101, 23))
        self.Update_Choose_path_btn.setObjectName("Update_Choose_path_btn")
        self.horizontalLayout_48.addWidget(self.Update_Choose_path_btn)
        self.verticalLayout_26.addLayout(self.horizontalLayout_48)
        self.Update_Upload_btn = QtWidgets.QPushButton(self.tab_11)
        self.Update_Upload_btn.setMinimumSize(QtCore.QSize(75, 23))
        self.Update_Upload_btn.setMaximumSize(QtCore.QSize(75, 23))
        self.Update_Upload_btn.setObjectName("Update_Upload_btn")
        self.verticalLayout_26.addWidget(self.Update_Upload_btn)
        self.tabWidget.addTab(self.tab_11, "")
        self.verticalLayout_10.addWidget(self.tabWidget)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.verticalLayout_10.addLayout(self.formLayout_2)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.Save_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Save_btn.setMinimumSize(QtCore.QSize(75, 23))
        self.Save_btn.setMaximumSize(QtCore.QSize(75, 23))
        self.Save_btn.setObjectName("Save_btn")
        self.horizontalLayout_38.addWidget(self.Save_btn)
        self.Load_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Load_btn.setMinimumSize(QtCore.QSize(75, 23))
        self.Load_btn.setMaximumSize(QtCore.QSize(75, 23))
        self.Load_btn.setObjectName("Load_btn")
        self.horizontalLayout_38.addWidget(self.Load_btn)
        self.verticalLayout_10.addLayout(self.horizontalLayout_38)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(10)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "WAN Settings"))
        self.Use_DHCP.setText(_translate("MainWindow", "Use DHCP"))
        self.label_2.setText(_translate("MainWindow", "IP address"))
        self.label_3.setText(_translate("MainWindow", "Netmask"))
        self.label_4.setText(_translate("MainWindow", "Default Gateway"))
        self.label_5.setText(_translate("MainWindow", "Hostname"))
        self.label_6.setText(_translate("MainWindow", "Domain"))
        self.label_7.setText(_translate("MainWindow", "DNS"))
        self.label_8.setText(_translate("MainWindow", "SSl"))
        self.SSI.setItemText(0, _translate("MainWindow", "Yes"))
        self.SSI.setItemText(1, _translate("MainWindow", "No"))
        self.label_9.setText(_translate("MainWindow", "SMTP Server"))
        self.label_10.setText(_translate("MainWindow", "IP address"))
        self.label_11.setText(_translate("MainWindow", "Port"))
        self.label_12.setText(_translate("MainWindow", "Source"))
        self.label_17.setText(_translate("MainWindow", "Change password"))
        self.label_18.setText(_translate("MainWindow", "Old password"))
        self.label_19.setText(_translate("MainWindow", "New password"))
        self.label_20.setText(_translate("MainWindow", "Confirm password"))
        self.Use_NTP.setText(_translate("MainWindow", "Use NTP"))
        self.label_26.setText(_translate("MainWindow", "NTP server"))
        self.Add_btn.setText(_translate("MainWindow", "Add"))
        self.Del_btn.setText(_translate("MainWindow", "Del"))
        self.label_27.setText(_translate("MainWindow", "TimeZone"))
        self.TimeZone.setItemText(0, _translate("MainWindow", "Los Angeles"))
        self.TimeZone.setItemText(1, _translate("MainWindow", "Chicago"))
        self.TimeZone.setItemText(2, _translate("MainWindow", "New York"))
        self.TimeZone.setItemText(3, _translate("MainWindow", "GMT"))
        self.TimeZone.setItemText(4, _translate("MainWindow", "London"))
        self.TimeZone.setItemText(5, _translate("MainWindow", "Berlin"))
        self.TimeZone.setItemText(6, _translate("MainWindow", "Moscow"))
        self.TimeZone.setItemText(7, _translate("MainWindow", "Mumbai"))
        self.TimeZone.setItemText(8, _translate("MainWindow", "Singapore"))
        self.TimeZone.setItemText(9, _translate("MainWindow", "Tokyo"))
        self.TimeZone.setItemText(10, _translate("MainWindow", "Sydney"))
        self.label_25.setText(_translate("MainWindow", "Date/Time Settings"))
        self.label_28.setText(_translate("MainWindow", "Date(dd/mm/yyyy)"))
        self.label_33.setText(_translate("MainWindow", " /"))
        self.label_35.setText(_translate("MainWindow", " /"))
        self.label_29.setText(_translate("MainWindow", "Time(hh:mm)"))
        self.label_34.setText(_translate("MainWindow", " :"))
        self.label_13.setText(_translate("MainWindow", "SIP registrar"))
        self.label_14.setText(_translate("MainWindow", "Name"))
        self.label_15.setText(_translate("MainWindow", "Unicast port"))
        self.label_16.setText(_translate("MainWindow", "Multicast port"))
        self.label_21.setText(_translate("MainWindow", "H.323 gatekeeper"))
        self.label_22.setText(_translate("MainWindow", "Name"))
        self.label_23.setText(_translate("MainWindow", "Unicast"))
        self.label_24.setText(_translate("MainWindow", "Multicast port"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Configuration"))
        self.Users_edit_btn.setText(_translate("MainWindow", "Add"))
        self.Action_options.setTitle(_translate("MainWindow", "Action options"))
        self.Del_Radio.setText(_translate("MainWindow", "Delete"))
        self.Edit_Radio.setText(_translate("MainWindow", "Edit"))
        item = self.Users_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Enabled"))
        item = self.Users_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Phone"))
        item = self.Users_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Name"))
        item = self.Users_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Address"))
        item = self.Users_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Status"))
        item = self.Users_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Action"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Users"))
        self.Gateways_Add_btn.setText(_translate("MainWindow", "Add"))
        self.Action_options_2.setTitle(_translate("MainWindow", "Action options"))
        self.Del_Radio_2.setText(_translate("MainWindow", "Delete"))
        self.Edit_Radio_2.setText(_translate("MainWindow", "Edit"))
        item = self.Gateways_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Enabled"))
        item = self.Gateways_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.Gateways_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Status"))
        item = self.Gateways_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Action"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Gateways"))
        self.Services_Add_btn.setText(_translate("MainWindow", "Add"))
        self.Action_options_3.setTitle(_translate("MainWindow", "Action options"))
        self.Del_Radio_3.setText(_translate("MainWindow", "Delete"))
        self.Edit_Radio_3.setText(_translate("MainWindow", "Edit"))
        item = self.Services_Table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Enabled"))
        item = self.Services_Table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.Services_Table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Command"))
        item = self.Services_Table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Action"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Services"))
        self.Routes_Add_btn.setText(_translate("MainWindow", "Add"))
        self.Action_options_4.setTitle(_translate("MainWindow", "Action options"))
        self.Del_Radio_4.setText(_translate("MainWindow", "Delete"))
        self.Edit_Radio_4.setText(_translate("MainWindow", "Edit"))
        item = self.Routes_Table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Enabled"))
        item = self.Routes_Table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.Routes_Table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Criteria"))
        item = self.Routes_Table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Match"))
        item = self.Routes_Table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Pattern"))
        item = self.Routes_Table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Result"))
        item = self.Routes_Table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Command"))
        item = self.Routes_Table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Argument"))
        item = self.Routes_Table.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Action"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Routes"))
        self.Groups_Add_btn.setText(_translate("MainWindow", "Add"))
        self.Action_options_5.setTitle(_translate("MainWindow", "Action options"))
        self.Del_Radio_5.setText(_translate("MainWindow", "Delete"))
        self.Edit_Radio_5.setText(_translate("MainWindow", "Edit"))
        item = self.Groups_Table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Enabled"))
        item = self.Groups_Table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.Groups_Table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Type"))
        item = self.Groups_Table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Transfer"))
        item = self.Groups_Table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Forward"))
        item = self.Groups_Table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Conference"))
        item = self.Groups_Table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Call waiting"))
        item = self.Groups_Table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Action"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Groups"))
        self.label_36.setText(_translate("MainWindow", "Upload prompt"))
        self.Pro_Choose_path_btn.setText(_translate("MainWindow", "Choose path"))
        self.label_31.setText(_translate("MainWindow", "Name"))
        self.Pro_Upload_btn.setText(_translate("MainWindow", "Upload"))
        self.Action_options_6.setTitle(_translate("MainWindow", "Action options"))
        self.Del_Radio_6.setText(_translate("MainWindow", "Delete"))
        self.Edit_Radio_6.setText(_translate("MainWindow", "Play"))
        self.label_30.setText(_translate("MainWindow", "Prompts configuration"))
        item = self.Prompts_Table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Prompt name"))
        item = self.Prompts_Table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Action"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "Prompts"))
        self.Rad_Ecb.setText(_translate("MainWindow", "Enabled"))
        self.label_43.setText(_translate("MainWindow", "Secret"))
        self.label_42.setText(_translate("MainWindow", "Retransmission count"))
        self.label_41.setText(_translate("MainWindow", "Retransmission interval"))
        self.label_40.setText(_translate("MainWindow", "Interim msg send interval"))
        self.label_39.setText(_translate("MainWindow", "Max call time"))
        self.label_38.setText(_translate("MainWindow", "Service type"))
        self.label_37.setText(_translate("MainWindow", "Framed protocol"))
        self.label_32.setText(_translate("MainWindow", "NAS IP"))
        self.Rad_Disc.setText(_translate("MainWindow", "Disconnect on accounting reject"))
        self.Rad_Auth_reg.setText(_translate("MainWindow", "Authorize registration"))
        self.Rad_Auth_call.setText(_translate("MainWindow", "Authorize call"))
        self.Rad_send_boot.setText(_translate("MainWindow", "Send boot"))
        self.Rad_Send_accounting.setText(_translate("MainWindow", "Send accounting"))
        self.Rad_Send_interim.setText(_translate("MainWindow", "Send interim"))
        self.Rad_Cisco_comp.setText(_translate("MainWindow", "Cisco compatible call ID"))
        self.Rad_Send_called.setText(_translate("MainWindow", "Send called station ID"))
        self.label_44.setText(_translate("MainWindow", "Server auth. / accounting addresses"))
        self.Rad_Add_server_btn.setText(_translate("MainWindow", "Add"))
        self.Rad_Add_server_btn_2.setText(_translate("MainWindow", "Del"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "Radius"))
        item = self.Statistics_Table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.Statistics_Table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.Statistics_Table.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.Statistics_Table.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.Statistics_Table.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.Statistics_Table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Time"))
        item = self.Statistics_Table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Direction"))
        item = self.Statistics_Table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Remote number"))
        item = self.Statistics_Table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Remote party"))
        item = self.Statistics_Table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Reason"))
        __sortingEnabled = self.Statistics_Table.isSortingEnabled()
        self.Statistics_Table.setSortingEnabled(False)
        item = self.Statistics_Table.item(0, 0)
        item.setText(_translate("MainWindow", "04/21/2006"))
        item = self.Statistics_Table.item(0, 1)
        item.setText(_translate("MainWindow", "outgoing"))
        item = self.Statistics_Table.item(0, 2)
        item.setText(_translate("MainWindow", "88312788872"))
        item = self.Statistics_Table.item(0, 3)
        item.setText(_translate("MainWindow", "sipnet.ru"))
        item = self.Statistics_Table.item(0, 4)
        item.setText(_translate("MainWindow", "Normal call"))
        item = self.Statistics_Table.item(1, 0)
        item.setText(_translate("MainWindow", "05/21/2006"))
        item = self.Statistics_Table.item(1, 1)
        item.setText(_translate("MainWindow", "outgoing"))
        item = self.Statistics_Table.item(1, 2)
        item.setText(_translate("MainWindow", "88312788872"))
        item = self.Statistics_Table.item(1, 3)
        item.setText(_translate("MainWindow", "sipnet.ru"))
        item = self.Statistics_Table.item(1, 4)
        item.setText(_translate("MainWindow", "Normal call"))
        item = self.Statistics_Table.item(2, 0)
        item.setText(_translate("MainWindow", "04/20/2006"))
        item = self.Statistics_Table.item(2, 1)
        item.setText(_translate("MainWindow", "outgoing"))
        item = self.Statistics_Table.item(2, 2)
        item.setText(_translate("MainWindow", "88312788872"))
        item = self.Statistics_Table.item(2, 3)
        item.setText(_translate("MainWindow", "sipnet.ru"))
        item = self.Statistics_Table.item(2, 4)
        item.setText(_translate("MainWindow", "Normal call"))
        item = self.Statistics_Table.item(3, 0)
        item.setText(_translate("MainWindow", "01/19/2006"))
        item = self.Statistics_Table.item(3, 1)
        item.setText(_translate("MainWindow", "outgoing"))
        item = self.Statistics_Table.item(3, 2)
        item.setText(_translate("MainWindow", "88312788872"))
        item = self.Statistics_Table.item(3, 3)
        item.setText(_translate("MainWindow", "sipnet.ru"))
        item = self.Statistics_Table.item(3, 4)
        item.setText(_translate("MainWindow", "Normal call"))
        item = self.Statistics_Table.item(4, 0)
        item.setText(_translate("MainWindow", "05/21/2005"))
        item = self.Statistics_Table.item(4, 1)
        item.setText(_translate("MainWindow", "outgoing"))
        item = self.Statistics_Table.item(4, 2)
        item.setText(_translate("MainWindow", "88312788872"))
        item = self.Statistics_Table.item(4, 3)
        item.setText(_translate("MainWindow", "sipnet.ru"))
        item = self.Statistics_Table.item(4, 4)
        item.setText(_translate("MainWindow", "Normal call"))
        self.Statistics_Table.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("MainWindow", "Statistics"))
        self.label_45.setText(_translate("MainWindow", "Keep Logs for"))
        self.label_46.setText(_translate("MainWindow", "Keep User CDRs for"))
        self.label_47.setText(_translate("MainWindow", "Keep Administrator CDRs for"))
        self.label_48.setText(_translate("MainWindow", "Email CDB to"))
        self.label_49.setText(_translate("MainWindow", "days"))
        self.label_50.setText(_translate("MainWindow", "days"))
        self.label_51.setText(_translate("MainWindow", "months"))
        item = self.Logs_Table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.Logs_Table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.Logs_Table.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.Logs_Table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Date"))
        item = self.Logs_Table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "File name"))
        __sortingEnabled = self.Logs_Table.isSortingEnabled()
        self.Logs_Table.setSortingEnabled(False)
        item = self.Logs_Table.item(0, 0)
        item.setText(_translate("MainWindow", "2007.11.20"))
        item = self.Logs_Table.item(0, 1)
        item.setText(_translate("MainWindow", "Logic-11-21.log"))
        item = self.Logs_Table.item(1, 0)
        item.setText(_translate("MainWindow", "2007.11.20"))
        item = self.Logs_Table.item(1, 1)
        item.setText(_translate("MainWindow", "Logic-12-11.log"))
        item = self.Logs_Table.item(2, 0)
        item.setText(_translate("MainWindow", "2007.11.20"))
        item = self.Logs_Table.item(2, 1)
        item.setText(_translate("MainWindow", "Logic-10-21.log"))
        self.Logs_Table.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_10), _translate("MainWindow", "Logs"))
        self.label_53.setText(_translate("MainWindow", "Application updates"))
        self.Action_options_7.setTitle(_translate("MainWindow", "Action options"))
        self.Del_Radio_7.setText(_translate("MainWindow", "Delete"))
        self.Edit_Radio_7.setText(_translate("MainWindow", "Activate"))
        item = self.Update_Table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Active"))
        item = self.Update_Table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Date"))
        item = self.Update_Table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Name"))
        item = self.Update_Table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Action"))
        self.label_55.setText(_translate("MainWindow", "Name"))
        self.label_54.setText(_translate("MainWindow", "Upload new version"))
        self.Update_Choose_path_btn.setText(_translate("MainWindow", "Choose path"))
        self.Update_Upload_btn.setText(_translate("MainWindow", "Upload"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_11), _translate("MainWindow", "Update"))
        self.Save_btn.setText(_translate("MainWindow", "Save"))
        self.Load_btn.setText(_translate("MainWindow", "Load"))

