# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Gui_for_Gateway.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Gateway_forma(object):
    def setupUi(self, Gateway_forma):
        Gateway_forma.setObjectName("Gateway_forma")
        Gateway_forma.resize(695, 756)
        self.centralwidget = QtWidgets.QWidget(Gateway_forma)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.Check_enable = QtWidgets.QCheckBox(self.centralwidget)
        self.Check_enable.setObjectName("Check_enable")
        self.verticalLayout_7.addWidget(self.Check_enable)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setMinimumSize(QtCore.QSize(111, 27))
        self.label_7.setMaximumSize(QtCore.QSize(111, 27))
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setMinimumSize(QtCore.QSize(111, 27))
        self.label_6.setMaximumSize(QtCore.QSize(111, 27))
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setMinimumSize(QtCore.QSize(111, 27))
        self.label_8.setMaximumSize(QtCore.QSize(111, 27))
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setMinimumSize(QtCore.QSize(111, 27))
        self.label_31.setMaximumSize(QtCore.QSize(111, 27))
        self.label_31.setObjectName("label_31")
        self.verticalLayout.addWidget(self.label_31)
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setMinimumSize(QtCore.QSize(111, 27))
        self.label_35.setMaximumSize(QtCore.QSize(111, 27))
        self.label_35.setObjectName("label_35")
        self.verticalLayout.addWidget(self.label_35)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Gateway_name = QtWidgets.QLineEdit(self.centralwidget)
        self.Gateway_name.setObjectName("Gateway_name")
        self.verticalLayout_2.addWidget(self.Gateway_name)
        self.Signaling = QtWidgets.QLineEdit(self.centralwidget)
        self.Signaling.setObjectName("Signaling")
        self.verticalLayout_2.addWidget(self.Signaling)
        self.IP_Address = QtWidgets.QLineEdit(self.centralwidget)
        self.IP_Address.setObjectName("IP_Address")
        self.verticalLayout_2.addWidget(self.IP_Address)
        self.IP_Port = QtWidgets.QLineEdit(self.centralwidget)
        self.IP_Port.setObjectName("IP_Port")
        self.verticalLayout_2.addWidget(self.IP_Port)
        self.DS_error_han = QtWidgets.QComboBox(self.centralwidget)
        self.DS_error_han.setObjectName("DS_error_han")
        self.DS_error_han.addItem("")
        self.DS_error_han.addItem("")
        self.DS_error_han.addItem("")
        self.verticalLayout_2.addWidget(self.DS_error_han)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setMinimumSize(QtCore.QSize(47, 13))
        self.label_21.setObjectName("label_21")
        self.verticalLayout_6.addWidget(self.label_21)
        self.Check_relay = QtWidgets.QCheckBox(self.centralwidget)
        self.Check_relay.setObjectName("Check_relay")
        self.verticalLayout_6.addWidget(self.Check_relay)
        self.Check_Trust = QtWidgets.QCheckBox(self.centralwidget)
        self.Check_Trust.setObjectName("Check_Trust")
        self.verticalLayout_6.addWidget(self.Check_Trust)
        self.Check_send = QtWidgets.QCheckBox(self.centralwidget)
        self.Check_send.setObjectName("Check_send")
        self.verticalLayout_6.addWidget(self.Check_send)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMinimumSize(QtCore.QSize(111, 27))
        self.label_5.setMaximumSize(QtCore.QSize(111, 27))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(111, 27))
        self.label_3.setMaximumSize(QtCore.QSize(111, 27))
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(111, 27))
        self.label_2.setMaximumSize(QtCore.QSize(111, 27))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setMinimumSize(QtCore.QSize(111, 27))
        self.label_9.setMaximumSize(QtCore.QSize(111, 27))
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Registration = QtWidgets.QComboBox(self.centralwidget)
        self.Registration.setObjectName("Registration")
        self.Registration.addItem("")
        self.Registration.addItem("")
        self.Registration.addItem("")
        self.verticalLayout_4.addWidget(self.Registration)
        self.Login_registr = QtWidgets.QLineEdit(self.centralwidget)
        self.Login_registr.setObjectName("Login_registr")
        self.verticalLayout_4.addWidget(self.Login_registr)
        self.Password_registr = QtWidgets.QLineEdit(self.centralwidget)
        self.Password_registr.setObjectName("Password_registr")
        self.verticalLayout_4.addWidget(self.Password_registr)
        self.TTL_registr = QtWidgets.QLineEdit(self.centralwidget)
        self.TTL_registr.setObjectName("TTL_registr")
        self.verticalLayout_4.addWidget(self.TTL_registr)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.Check_register_with = QtWidgets.QCheckBox(self.centralwidget)
        self.Check_register_with.setObjectName("Check_register_with")
        self.verticalLayout_7.addWidget(self.Check_register_with)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setMinimumSize(QtCore.QSize(111, 27))
        self.label_16.setMaximumSize(QtCore.QSize(111, 27))
        self.label_16.setObjectName("label_16")
        self.verticalLayout_8.addWidget(self.label_16)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setMinimumSize(QtCore.QSize(111, 27))
        self.label_15.setMaximumSize(QtCore.QSize(111, 27))
        self.label_15.setObjectName("label_15")
        self.verticalLayout_8.addWidget(self.label_15)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setMinimumSize(QtCore.QSize(111, 27))
        self.label_13.setMaximumSize(QtCore.QSize(111, 27))
        self.label_13.setObjectName("label_13")
        self.verticalLayout_8.addWidget(self.label_13)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setMinimumSize(QtCore.QSize(111, 27))
        self.label_12.setMaximumSize(QtCore.QSize(111, 27))
        self.label_12.setObjectName("label_12")
        self.verticalLayout_8.addWidget(self.label_12)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setMinimumSize(QtCore.QSize(111, 27))
        self.label_14.setMaximumSize(QtCore.QSize(111, 27))
        self.label_14.setObjectName("label_14")
        self.verticalLayout_8.addWidget(self.label_14)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setMinimumSize(QtCore.QSize(111, 27))
        self.label_11.setMaximumSize(QtCore.QSize(111, 27))
        self.label_11.setObjectName("label_11")
        self.verticalLayout_8.addWidget(self.label_11)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setMinimumSize(QtCore.QSize(111, 27))
        self.label_10.setMaximumSize(QtCore.QSize(111, 27))
        self.label_10.setObjectName("label_10")
        self.verticalLayout_8.addWidget(self.label_10)
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setMinimumSize(QtCore.QSize(111, 27))
        self.label_17.setMaximumSize(QtCore.QSize(111, 27))
        self.label_17.setObjectName("label_17")
        self.verticalLayout_8.addWidget(self.label_17)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.Reg_Ser_name = QtWidgets.QLineEdit(self.centralwidget)
        self.Reg_Ser_name.setObjectName("Reg_Ser_name")
        self.verticalLayout_9.addWidget(self.Reg_Ser_name)
        self.Reg_address = QtWidgets.QLineEdit(self.centralwidget)
        self.Reg_address.setObjectName("Reg_address")
        self.verticalLayout_9.addWidget(self.Reg_address)
        self.Reg_Port = QtWidgets.QLineEdit(self.centralwidget)
        self.Reg_Port.setObjectName("Reg_Port")
        self.verticalLayout_9.addWidget(self.Reg_Port)
        self.Reg_Login = QtWidgets.QLineEdit(self.centralwidget)
        self.Reg_Login.setObjectName("Reg_Login")
        self.verticalLayout_9.addWidget(self.Reg_Login)
        self.Reg_password = QtWidgets.QLineEdit(self.centralwidget)
        self.Reg_password.setObjectName("Reg_password")
        self.verticalLayout_9.addWidget(self.Reg_password)
        self.Reg_TTL = QtWidgets.QLineEdit(self.centralwidget)
        self.Reg_TTL.setObjectName("Reg_TTL")
        self.verticalLayout_9.addWidget(self.Reg_TTL)
        self.Reg_Security_type = QtWidgets.QLineEdit(self.centralwidget)
        self.Reg_Security_type.setObjectName("Reg_Security_type")
        self.verticalLayout_9.addWidget(self.Reg_Security_type)
        self.Reg_Endpoint_type = QtWidgets.QLineEdit(self.centralwidget)
        self.Reg_Endpoint_type.setObjectName("Reg_Endpoint_type")
        self.verticalLayout_9.addWidget(self.Reg_Endpoint_type)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_9.addLayout(self.verticalLayout_7)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_41 = QtWidgets.QLabel(self.centralwidget)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_14.addWidget(self.label_41)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setMinimumSize(QtCore.QSize(111, 27))
        self.label_23.setMaximumSize(QtCore.QSize(111, 27))
        self.label_23.setObjectName("label_23")
        self.verticalLayout_12.addWidget(self.label_23)
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setMinimumSize(QtCore.QSize(111, 27))
        self.label_19.setMaximumSize(QtCore.QSize(111, 27))
        self.label_19.setObjectName("label_19")
        self.verticalLayout_12.addWidget(self.label_19)
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setMinimumSize(QtCore.QSize(111, 27))
        self.label_24.setMaximumSize(QtCore.QSize(111, 27))
        self.label_24.setObjectName("label_24")
        self.verticalLayout_12.addWidget(self.label_24)
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setMinimumSize(QtCore.QSize(111, 27))
        self.label_18.setMaximumSize(QtCore.QSize(111, 27))
        self.label_18.setObjectName("label_18")
        self.verticalLayout_12.addWidget(self.label_18)
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setMinimumSize(QtCore.QSize(111, 27))
        self.label_22.setMaximumSize(QtCore.QSize(111, 27))
        self.label_22.setObjectName("label_22")
        self.verticalLayout_12.addWidget(self.label_22)
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setMinimumSize(QtCore.QSize(111, 27))
        self.label_25.setMaximumSize(QtCore.QSize(111, 27))
        self.label_25.setObjectName("label_25")
        self.verticalLayout_12.addWidget(self.label_25)
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setMinimumSize(QtCore.QSize(111, 27))
        self.label_30.setMaximumSize(QtCore.QSize(111, 27))
        self.label_30.setObjectName("label_30")
        self.verticalLayout_12.addWidget(self.label_30)
        self.horizontalLayout_5.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.Gen_NAT = QtWidgets.QLineEdit(self.centralwidget)
        self.Gen_NAT.setObjectName("Gen_NAT")
        self.verticalLayout_13.addWidget(self.Gen_NAT)
        self.Gen_Fax = QtWidgets.QLineEdit(self.centralwidget)
        self.Gen_Fax.setObjectName("Gen_Fax")
        self.verticalLayout_13.addWidget(self.Gen_Fax)
        self.Gen_conv = QtWidgets.QLineEdit(self.centralwidget)
        self.Gen_conv.setObjectName("Gen_conv")
        self.verticalLayout_13.addWidget(self.Gen_conv)
        self.Gen_repack = QtWidgets.QLineEdit(self.centralwidget)
        self.Gen_repack.setObjectName("Gen_repack")
        self.verticalLayout_13.addWidget(self.Gen_repack)
        self.Gen_DTMF = QtWidgets.QLineEdit(self.centralwidget)
        self.Gen_DTMF.setObjectName("Gen_DTMF")
        self.verticalLayout_13.addWidget(self.Gen_DTMF)
        self.Gen_Early_Connect = QtWidgets.QLineEdit(self.centralwidget)
        self.Gen_Early_Connect.setObjectName("Gen_Early_Connect")
        self.verticalLayout_13.addWidget(self.Gen_Early_Connect)
        self.Gen_Proxy_RBT = QtWidgets.QLineEdit(self.centralwidget)
        self.Gen_Proxy_RBT.setObjectName("Gen_Proxy_RBT")
        self.verticalLayout_13.addWidget(self.Gen_Proxy_RBT)
        self.horizontalLayout_5.addLayout(self.verticalLayout_13)
        self.verticalLayout_14.addLayout(self.horizontalLayout_5)
        self.label_42 = QtWidgets.QLabel(self.centralwidget)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_14.addWidget(self.label_42)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setMinimumSize(QtCore.QSize(111, 27))
        self.label_32.setMaximumSize(QtCore.QSize(111, 27))
        self.label_32.setObjectName("label_32")
        self.verticalLayout_16.addWidget(self.label_32)
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setMinimumSize(QtCore.QSize(111, 27))
        self.label_33.setMaximumSize(QtCore.QSize(111, 27))
        self.label_33.setObjectName("label_33")
        self.verticalLayout_16.addWidget(self.label_33)
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setMinimumSize(QtCore.QSize(111, 27))
        self.label_34.setMaximumSize(QtCore.QSize(111, 27))
        self.label_34.setObjectName("label_34")
        self.verticalLayout_16.addWidget(self.label_34)
        self.horizontalLayout_7.addLayout(self.verticalLayout_16)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.SIP_Ringback_Tone = QtWidgets.QLineEdit(self.centralwidget)
        self.SIP_Ringback_Tone.setObjectName("SIP_Ringback_Tone")
        self.verticalLayout_15.addWidget(self.SIP_Ringback_Tone)
        self.SIP_Allow_Sip_Red = QtWidgets.QLineEdit(self.centralwidget)
        self.SIP_Allow_Sip_Red.setObjectName("SIP_Allow_Sip_Red")
        self.verticalLayout_15.addWidget(self.SIP_Allow_Sip_Red)
        self.SIP_Allow_noproxy = QtWidgets.QLineEdit(self.centralwidget)
        self.SIP_Allow_noproxy.setObjectName("SIP_Allow_noproxy")
        self.verticalLayout_15.addWidget(self.SIP_Allow_noproxy)
        self.horizontalLayout_7.addLayout(self.verticalLayout_15)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setMinimumSize(QtCore.QSize(121, 16))
        self.label_20.setObjectName("label_20")
        self.verticalLayout_5.addWidget(self.label_20)
        self.Codec_Table = QtWidgets.QTableWidget(self.centralwidget)
        self.Codec_Table.setObjectName("Codec_Table")
        self.Codec_Table.setColumnCount(3)
        self.Codec_Table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Codec_Table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Codec_Table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Codec_Table.setHorizontalHeaderItem(2, item)
        self.verticalLayout_5.addWidget(self.Codec_Table)
        self.Gateways_add_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Gateways_add_btn.setObjectName("Gateways_add_btn")
        self.verticalLayout_5.addWidget(self.Gateways_add_btn)
        self.verticalLayout_14.addLayout(self.verticalLayout_5)
        self.horizontalLayout_9.addLayout(self.verticalLayout_14)
        self.verticalLayout_10.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.Nazad_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Nazad_btn.setObjectName("Nazad_btn")
        self.horizontalLayout_8.addWidget(self.Nazad_btn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.create_btn = QtWidgets.QPushButton(self.centralwidget)
        self.create_btn.setObjectName("create_btn")
        self.horizontalLayout_8.addWidget(self.create_btn)
        self.verticalLayout_10.addLayout(self.horizontalLayout_8)
        Gateway_forma.setCentralWidget(self.centralwidget)

        self.retranslateUi(Gateway_forma)
        QtCore.QMetaObject.connectSlotsByName(Gateway_forma)

    def retranslateUi(self, Gateway_forma):
        _translate = QtCore.QCoreApplication.translate
        Gateway_forma.setWindowTitle(_translate("Gateway_forma", "MainWindow"))
        self.Check_enable.setText(_translate("Gateway_forma", "Enabled"))
        self.label_7.setText(_translate("Gateway_forma", "Gateway name"))
        self.label_6.setText(_translate("Gateway_forma", "Signaling"))
        self.label_8.setText(_translate("Gateway_forma", "IP Address"))
        self.label_31.setText(_translate("Gateway_forma", "IP Port"))
        self.label_35.setText(_translate("Gateway_forma", "Dst leg error handling"))
        self.DS_error_han.setItemText(0, _translate("Gateway_forma", "Play prompt"))
        self.DS_error_han.setItemText(1, _translate("Gateway_forma", "Disconnect src"))
        self.DS_error_han.setItemText(2, _translate("Gateway_forma", "Connect and play prompt"))
        self.label_21.setText(_translate("Gateway_forma", "Caller IDs"))
        self.Check_relay.setText(_translate("Gateway_forma", "Relay Incoming"))
        self.Check_Trust.setText(_translate("Gateway_forma", "Trust Incoming"))
        self.Check_send.setText(_translate("Gateway_forma", "Send"))
        self.label_5.setText(_translate("Gateway_forma", "Registration"))
        self.label_3.setText(_translate("Gateway_forma", "Login"))
        self.label_2.setText(_translate("Gateway_forma", "Password"))
        self.label_9.setText(_translate("Gateway_forma", "TTL"))
        self.Registration.setItemText(0, _translate("Gateway_forma", "Enabled"))
        self.Registration.setItemText(1, _translate("Gateway_forma", "Required"))
        self.Registration.setItemText(2, _translate("Gateway_forma", "Disabled"))
        self.Check_register_with.setText(_translate("Gateway_forma", "Register with GK/registres"))
        self.label_16.setText(_translate("Gateway_forma", "Server name"))
        self.label_15.setText(_translate("Gateway_forma", "Address"))
        self.label_13.setText(_translate("Gateway_forma", "Port"))
        self.label_12.setText(_translate("Gateway_forma", "Login"))
        self.label_14.setText(_translate("Gateway_forma", "Password"))
        self.label_11.setText(_translate("Gateway_forma", "TTL"))
        self.label_10.setText(_translate("Gateway_forma", "Security type"))
        self.label_17.setText(_translate("Gateway_forma", "Endpoint type"))
        self.label_41.setText(_translate("Gateway_forma", "General options"))
        self.label_23.setText(_translate("Gateway_forma", "NAT"))
        self.label_19.setText(_translate("Gateway_forma", "Fax T.38"))
        self.label_24.setText(_translate("Gateway_forma", "Convert"))
        self.label_18.setText(_translate("Gateway_forma", "Repacketize"))
        self.label_22.setText(_translate("Gateway_forma", "DTMF Options"))
        self.label_25.setText(_translate("Gateway_forma", "Early Connect"))
        self.label_30.setText(_translate("Gateway_forma", "Proxy RBT"))
        self.label_42.setText(_translate("Gateway_forma", "SIP options"))
        self.label_32.setText(_translate("Gateway_forma", "Ringback Tone"))
        self.label_33.setText(_translate("Gateway_forma", "Allow Sip Redirect"))
        self.label_34.setText(_translate("Gateway_forma", "Allow noproxy"))
        self.label_20.setText(_translate("Gateway_forma", "Codecs configuration"))
        item = self.Codec_Table.horizontalHeaderItem(0)
        item.setText(_translate("Gateway_forma", "Codec"))
        item = self.Codec_Table.horizontalHeaderItem(1)
        item.setText(_translate("Gateway_forma", "FFP"))
        item = self.Codec_Table.horizontalHeaderItem(2)
        item.setText(_translate("Gateway_forma", "Action"))
        self.Gateways_add_btn.setText(_translate("Gateway_forma", "Add"))
        self.Nazad_btn.setText(_translate("Gateway_forma", "Назад"))
        self.create_btn.setText(_translate("Gateway_forma", "Создать"))

