# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Gui_for_Routes.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Routes_forma(object):
    def setupUi(self, Routes_forma):
        Routes_forma.setObjectName("Routes_forma")
        Routes_forma.resize(560, 674)
        self.centralwidget = QtWidgets.QWidget(Routes_forma)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_8.addWidget(self.checkBox)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(81, 76))
        self.label.setMaximumSize(QtCore.QSize(81, 76))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.Route_name = QtWidgets.QLineEdit(self.centralwidget)
        self.Route_name.setMinimumSize(QtCore.QSize(131, 20))
        self.Route_name.setMaximumSize(QtCore.QSize(131, 20))
        self.Route_name.setObjectName("Route_name")
        self.horizontalLayout.addWidget(self.Route_name)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.horizontalLayout_5.addLayout(self.horizontalLayout)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(81, 16))
        self.label_2.setMaximumSize(QtCore.QSize(81, 16))
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(81, 16))
        self.label_3.setMaximumSize(QtCore.QSize(81, 16))
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Command_arg = QtWidgets.QComboBox(self.centralwidget)
        self.Command_arg.setMinimumSize(QtCore.QSize(131, 20))
        self.Command_arg.setMaximumSize(QtCore.QSize(131, 20))
        self.Command_arg.setObjectName("Command_arg")
        self.Command_arg.addItem("")
        self.Command_arg.addItem("")
        self.Command_arg.addItem("")
        self.verticalLayout_2.addWidget(self.Command_arg)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_7.addWidget(self.label_10)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_7.addWidget(self.label_5)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.Source_Match = QtWidgets.QLineEdit(self.centralwidget)
        self.Source_Match.setObjectName("Source_Match")
        self.verticalLayout_3.addWidget(self.Source_Match)
        self.Destination_Match = QtWidgets.QLineEdit(self.centralwidget)
        self.Destination_Match.setObjectName("Destination_Match")
        self.verticalLayout_3.addWidget(self.Destination_Match)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.Source_Pattern = QtWidgets.QLineEdit(self.centralwidget)
        self.Source_Pattern.setObjectName("Source_Pattern")
        self.verticalLayout_4.addWidget(self.Source_Pattern)
        self.Destination_Pattern = QtWidgets.QLineEdit(self.centralwidget)
        self.Destination_Pattern.setObjectName("Destination_Pattern")
        self.verticalLayout_4.addWidget(self.Destination_Pattern)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_5.addWidget(self.label_8)
        self.Source_result = QtWidgets.QLineEdit(self.centralwidget)
        self.Source_result.setObjectName("Source_result")
        self.verticalLayout_5.addWidget(self.Source_result)
        self.Destination_result = QtWidgets.QLineEdit(self.centralwidget)
        self.Destination_result.setObjectName("Destination_result")
        self.verticalLayout_5.addWidget(self.Destination_result)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_6.addWidget(self.label_9)
        self.Source_billing = QtWidgets.QLineEdit(self.centralwidget)
        self.Source_billing.setObjectName("Source_billing")
        self.verticalLayout_6.addWidget(self.Source_billing)
        self.Destination_Billing = QtWidgets.QLineEdit(self.centralwidget)
        self.Destination_Billing.setObjectName("Destination_Billing")
        self.verticalLayout_6.addWidget(self.Destination_Billing)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_8.addWidget(self.label_11)
        self.Routes_forma_Table = QtWidgets.QTableWidget(self.centralwidget)
        self.Routes_forma_Table.setObjectName("Routes_forma_Table")
        self.Routes_forma_Table.setColumnCount(2)
        self.Routes_forma_Table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Routes_forma_Table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Routes_forma_Table.setHorizontalHeaderItem(1, item)
        self.verticalLayout_8.addWidget(self.Routes_forma_Table)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.Add_Router_table = QtWidgets.QPushButton(self.centralwidget)
        self.Add_Router_table.setObjectName("Add_Router_table")
        self.horizontalLayout_8.addWidget(self.Add_Router_table)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.Nazad_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Nazad_btn.setMinimumSize(QtCore.QSize(81, 23))
        self.Nazad_btn.setMaximumSize(QtCore.QSize(81, 23))
        self.Nazad_btn.setObjectName("Nazad_btn")
        self.horizontalLayout_7.addWidget(self.Nazad_btn)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.Create_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Create_btn.setMinimumSize(QtCore.QSize(81, 23))
        self.Create_btn.setMaximumSize(QtCore.QSize(81, 23))
        self.Create_btn.setObjectName("Create_btn")
        self.horizontalLayout_7.addWidget(self.Create_btn)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        Routes_forma.setCentralWidget(self.centralwidget)

        self.retranslateUi(Routes_forma)
        QtCore.QMetaObject.connectSlotsByName(Routes_forma)

    def retranslateUi(self, Routes_forma):
        _translate = QtCore.QCoreApplication.translate
        Routes_forma.setWindowTitle(_translate("Routes_forma", "MainWindow"))
        self.checkBox.setText(_translate("Routes_forma", "Enabled"))
        self.label.setText(_translate("Routes_forma", "Route name"))
        self.label_2.setText(_translate("Routes_forma", "Command"))
        self.label_3.setText(_translate("Routes_forma", "Argument"))
        self.Command_arg.setItemText(0, _translate("Routes_forma", "Dial Gateway"))
        self.Command_arg.setItemText(1, _translate("Routes_forma", "Service"))
        self.Command_arg.setItemText(2, _translate("Routes_forma", "Argument"))
        self.label_4.setText(_translate("Routes_forma", "Source"))
        self.label_5.setText(_translate("Routes_forma", "Destination"))
        self.label_6.setText(_translate("Routes_forma", "Match"))
        self.label_7.setText(_translate("Routes_forma", "Pattern"))
        self.label_8.setText(_translate("Routes_forma", "Result"))
        self.label_9.setText(_translate("Routes_forma", "Billing"))
        self.label_11.setText(_translate("Routes_forma", "Activity schedule"))
        item = self.Routes_forma_Table.horizontalHeaderItem(0)
        item.setText(_translate("Routes_forma", "Schedule"))
        item = self.Routes_forma_Table.horizontalHeaderItem(1)
        item.setText(_translate("Routes_forma", "Action"))
        self.Add_Router_table.setText(_translate("Routes_forma", "Add"))
        self.Nazad_btn.setText(_translate("Routes_forma", "Назад"))
        self.Create_btn.setText(_translate("Routes_forma", "Создать"))

