# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Gui_users_reg_1_may.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Users_create(object):
    def setupUi(self, Users_create):
        Users_create.setObjectName("Users_create")
        Users_create.resize(625, 588)
        self.centralwidget = QtWidgets.QWidget(Users_create)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.check_Enabled = QtWidgets.QCheckBox(self.centralwidget)
        self.check_Enabled.setObjectName("check_Enabled")
        self.verticalLayout_3.addWidget(self.check_Enabled)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setMinimumSize(QtCore.QSize(81, 28))
        self.label_14.setMaximumSize(QtCore.QSize(81, 28))
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_11.addWidget(self.label_14)
        self.gur_User_name = QtWidgets.QLineEdit(self.centralwidget)
        self.gur_User_name.setObjectName("gur_User_name")
        self.horizontalLayout_11.addWidget(self.gur_User_name)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setMinimumSize(QtCore.QSize(81, 27))
        self.label_15.setMaximumSize(QtCore.QSize(81, 27))
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_12.addWidget(self.label_15)
        self.gur_Phone_num = QtWidgets.QLineEdit(self.centralwidget)
        self.gur_Phone_num.setObjectName("gur_Phone_num")
        self.horizontalLayout_12.addWidget(self.gur_Phone_num)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setMinimumSize(QtCore.QSize(81, 28))
        self.label_17.setMaximumSize(QtCore.QSize(81, 28))
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_14.addWidget(self.label_17)
        self.gur_Signaling = QtWidgets.QLineEdit(self.centralwidget)
        self.gur_Signaling.setObjectName("gur_Signaling")
        self.horizontalLayout_14.addWidget(self.gur_Signaling)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setMinimumSize(QtCore.QSize(81, 28))
        self.label_16.setMaximumSize(QtCore.QSize(81, 28))
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_13.addWidget(self.label_16)
        self.gur_IP_Address = QtWidgets.QLineEdit(self.centralwidget)
        self.gur_IP_Address.setObjectName("gur_IP_Address")
        self.horizontalLayout_13.addWidget(self.gur_IP_Address)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setMinimumSize(QtCore.QSize(81, 28))
        self.label_18.setMaximumSize(QtCore.QSize(81, 28))
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_15.addWidget(self.label_18)
        self.gur_IP_port = QtWidgets.QLineEdit(self.centralwidget)
        self.gur_IP_port.setObjectName("gur_IP_port")
        self.horizontalLayout_15.addWidget(self.gur_IP_port)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setMinimumSize(QtCore.QSize(81, 28))
        self.label_19.setMaximumSize(QtCore.QSize(81, 28))
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_16.addWidget(self.label_19)
        self.gur_Email = QtWidgets.QLineEdit(self.centralwidget)
        self.gur_Email.setObjectName("gur_Email")
        self.horizontalLayout_16.addWidget(self.gur_Email)
        self.verticalLayout_3.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setMinimumSize(QtCore.QSize(81, 28))
        self.label_20.setMaximumSize(QtCore.QSize(81, 28))
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_17.addWidget(self.label_20)
        self.gur_Pin_code = QtWidgets.QLineEdit(self.centralwidget)
        self.gur_Pin_code.setObjectName("gur_Pin_code")
        self.horizontalLayout_17.addWidget(self.gur_Pin_code)
        self.verticalLayout_3.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setMinimumSize(QtCore.QSize(81, 28))
        self.label_21.setMaximumSize(QtCore.QSize(81, 28))
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_18.addWidget(self.label_21)
        self.gur_Web_password = QtWidgets.QLineEdit(self.centralwidget)
        self.gur_Web_password.setObjectName("gur_Web_password")
        self.horizontalLayout_18.addWidget(self.gur_Web_password)
        self.verticalLayout_3.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        self.label_38.setMinimumSize(QtCore.QSize(81, 28))
        self.label_38.setMaximumSize(QtCore.QSize(81, 28))
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_32.addWidget(self.label_38)
        self.gur_Registration = QtWidgets.QComboBox(self.centralwidget)
        self.gur_Registration.setObjectName("gur_Registration")
        self.gur_Registration.addItem("")
        self.gur_Registration.addItem("")
        self.gur_Registration.addItem("")
        self.horizontalLayout_32.addWidget(self.gur_Registration)
        self.verticalLayout_3.addLayout(self.horizontalLayout_32)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_3.addWidget(self.comboBox)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_39 = QtWidgets.QLabel(self.centralwidget)
        self.label_39.setMinimumSize(QtCore.QSize(81, 27))
        self.label_39.setMaximumSize(QtCore.QSize(81, 27))
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_33.addWidget(self.label_39)
        self.gur_Login = QtWidgets.QLineEdit(self.centralwidget)
        self.gur_Login.setObjectName("gur_Login")
        self.horizontalLayout_33.addWidget(self.gur_Login)
        self.verticalLayout_3.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_40 = QtWidgets.QLabel(self.centralwidget)
        self.label_40.setMinimumSize(QtCore.QSize(81, 28))
        self.label_40.setMaximumSize(QtCore.QSize(81, 28))
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_34.addWidget(self.label_40)
        self.gur_Password = QtWidgets.QLineEdit(self.centralwidget)
        self.gur_Password.setObjectName("gur_Password")
        self.horizontalLayout_34.addWidget(self.gur_Password)
        self.verticalLayout_3.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_41 = QtWidgets.QLabel(self.centralwidget)
        self.label_41.setMinimumSize(QtCore.QSize(81, 28))
        self.label_41.setMaximumSize(QtCore.QSize(81, 28))
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_35.addWidget(self.label_41)
        self.gur_TTL = QtWidgets.QLineEdit(self.centralwidget)
        self.gur_TTL.setObjectName("gur_TTL")
        self.horizontalLayout_35.addWidget(self.gur_TTL)
        self.verticalLayout_3.addLayout(self.horizontalLayout_35)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_24.setObjectName("label_24")
        self.verticalLayout_4.addWidget(self.label_24)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setMinimumSize(QtCore.QSize(81, 28))
        self.label_25.setMaximumSize(QtCore.QSize(81, 28))
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_21.addWidget(self.label_25)
        self.gur_NAT = QtWidgets.QLineEdit(self.centralwidget)
        self.gur_NAT.setObjectName("gur_NAT")
        self.horizontalLayout_21.addWidget(self.gur_NAT)
        self.verticalLayout_4.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setMinimumSize(QtCore.QSize(81, 27))
        self.label_26.setMaximumSize(QtCore.QSize(81, 27))
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_22.addWidget(self.label_26)
        self.gur_Fax = QtWidgets.QLineEdit(self.centralwidget)
        self.gur_Fax.setObjectName("gur_Fax")
        self.horizontalLayout_22.addWidget(self.gur_Fax)
        self.verticalLayout_4.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setMinimumSize(QtCore.QSize(81, 28))
        self.label_27.setMaximumSize(QtCore.QSize(81, 28))
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_23.addWidget(self.label_27)
        self.gur_Convert = QtWidgets.QLineEdit(self.centralwidget)
        self.gur_Convert.setObjectName("gur_Convert")
        self.horizontalLayout_23.addWidget(self.gur_Convert)
        self.verticalLayout_4.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setMinimumSize(QtCore.QSize(81, 28))
        self.label_31.setMaximumSize(QtCore.QSize(81, 28))
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_27.addWidget(self.label_31)
        self.gur_Repacketize = QtWidgets.QLineEdit(self.centralwidget)
        self.gur_Repacketize.setObjectName("gur_Repacketize")
        self.horizontalLayout_27.addWidget(self.gur_Repacketize)
        self.verticalLayout_4.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setMinimumSize(QtCore.QSize(81, 28))
        self.label_28.setMaximumSize(QtCore.QSize(81, 28))
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_24.addWidget(self.label_28)
        self.gur_DTMF = QtWidgets.QLineEdit(self.centralwidget)
        self.gur_DTMF.setObjectName("gur_DTMF")
        self.horizontalLayout_24.addWidget(self.gur_DTMF)
        self.verticalLayout_4.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setMinimumSize(QtCore.QSize(81, 28))
        self.label_29.setMaximumSize(QtCore.QSize(81, 28))
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_25.addWidget(self.label_29)
        self.gur_Connect = QtWidgets.QLineEdit(self.centralwidget)
        self.gur_Connect.setObjectName("gur_Connect")
        self.horizontalLayout_25.addWidget(self.gur_Connect)
        self.verticalLayout_4.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setMinimumSize(QtCore.QSize(81, 28))
        self.label_30.setMaximumSize(QtCore.QSize(81, 28))
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_26.addWidget(self.label_30)
        self.gur_RBT = QtWidgets.QLineEdit(self.centralwidget)
        self.gur_RBT.setObjectName("gur_RBT")
        self.horizontalLayout_26.addWidget(self.gur_RBT)
        self.verticalLayout_4.addLayout(self.horizontalLayout_26)
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_33.setObjectName("label_33")
        self.verticalLayout_4.addWidget(self.label_33)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setMinimumSize(QtCore.QSize(81, 28))
        self.label_34.setMaximumSize(QtCore.QSize(81, 28))
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_29.addWidget(self.label_34)
        self.gur_Tone = QtWidgets.QLineEdit(self.centralwidget)
        self.gur_Tone.setObjectName("gur_Tone")
        self.horizontalLayout_29.addWidget(self.gur_Tone)
        self.verticalLayout_4.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setMinimumSize(QtCore.QSize(81, 28))
        self.label_35.setMaximumSize(QtCore.QSize(81, 28))
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_30.addWidget(self.label_35)
        self.gur_Sip = QtWidgets.QLineEdit(self.centralwidget)
        self.gur_Sip.setObjectName("gur_Sip")
        self.horizontalLayout_30.addWidget(self.gur_Sip)
        self.verticalLayout_4.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_36 = QtWidgets.QLabel(self.centralwidget)
        self.label_36.setMinimumSize(QtCore.QSize(81, 28))
        self.label_36.setMaximumSize(QtCore.QSize(81, 28))
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_31.addWidget(self.label_36)
        self.gur_noproxy = QtWidgets.QLineEdit(self.centralwidget)
        self.gur_noproxy.setObjectName("gur_noproxy")
        self.horizontalLayout_31.addWidget(self.gur_noproxy)
        self.verticalLayout_4.addLayout(self.horizontalLayout_31)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.Codec_Table = QtWidgets.QTableWidget(self.centralwidget)
        self.Codec_Table.setObjectName("Codec_Table")
        self.Codec_Table.setColumnCount(3)
        self.Codec_Table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Codec_Table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Codec_Table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Codec_Table.setHorizontalHeaderItem(2, item)
        self.verticalLayout_2.addWidget(self.Codec_Table)
        self.Add_Codec_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Add_Codec_btn.setObjectName("Add_Codec_btn")
        self.verticalLayout_2.addWidget(self.Add_Codec_btn)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.Group_Pikcup = QtWidgets.QCheckBox(self.centralwidget)
        self.Group_Pikcup.setObjectName("Group_Pikcup")
        self.verticalLayout.addWidget(self.Group_Pikcup)
        self.Group_Restricted = QtWidgets.QCheckBox(self.centralwidget)
        self.Group_Restricted.setObjectName("Group_Restricted")
        self.verticalLayout.addWidget(self.Group_Restricted)
        self.Group_All = QtWidgets.QCheckBox(self.centralwidget)
        self.Group_All.setObjectName("Group_All")
        self.verticalLayout.addWidget(self.Group_All)
        self.Group_Group_Call = QtWidgets.QCheckBox(self.centralwidget)
        self.Group_Group_Call.setObjectName("Group_Group_Call")
        self.verticalLayout.addWidget(self.Group_Group_Call)
        self.Group_Local_Users = QtWidgets.QCheckBox(self.centralwidget)
        self.Group_Local_Users.setObjectName("Group_Local_Users")
        self.verticalLayout.addWidget(self.Group_Local_Users)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.Call_Table = QtWidgets.QTableWidget(self.centralwidget)
        self.Call_Table.setObjectName("Call_Table")
        self.Call_Table.setColumnCount(6)
        self.Call_Table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Call_Table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Call_Table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Call_Table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Call_Table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Call_Table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Call_Table.setHorizontalHeaderItem(5, item)
        self.verticalLayout_5.addWidget(self.Call_Table)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Add_call_table_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Add_call_table_btn.setObjectName("Add_call_table_btn")
        self.horizontalLayout_3.addWidget(self.Add_call_table_btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Nazad_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Nazad_btn.setMinimumSize(QtCore.QSize(81, 23))
        self.Nazad_btn.setMaximumSize(QtCore.QSize(81, 23))
        self.Nazad_btn.setObjectName("Nazad_btn")
        self.horizontalLayout_2.addWidget(self.Nazad_btn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.Create_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Create_btn.setMinimumSize(QtCore.QSize(81, 23))
        self.Create_btn.setMaximumSize(QtCore.QSize(81, 23))
        self.Create_btn.setObjectName("Create_btn")
        self.horizontalLayout_2.addWidget(self.Create_btn)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        Users_create.setCentralWidget(self.centralwidget)

        self.retranslateUi(Users_create)
        QtCore.QMetaObject.connectSlotsByName(Users_create)

    def retranslateUi(self, Users_create):
        _translate = QtCore.QCoreApplication.translate
        Users_create.setWindowTitle(_translate("Users_create", "MainWindow"))
        self.check_Enabled.setText(_translate("Users_create", "Enabled"))
        self.label_14.setText(_translate("Users_create", "User name"))
        self.label_15.setText(_translate("Users_create", "Phone number"))
        self.label_17.setText(_translate("Users_create", "Signaling"))
        self.label_16.setText(_translate("Users_create", "IP Address"))
        self.label_18.setText(_translate("Users_create", "IP Port"))
        self.label_19.setText(_translate("Users_create", "E-mail"))
        self.label_20.setText(_translate("Users_create", "Pin code"))
        self.label_21.setText(_translate("Users_create", "Web password"))
        self.label_38.setText(_translate("Users_create", "Registration"))
        self.gur_Registration.setItemText(0, _translate("Users_create", "Enabled"))
        self.gur_Registration.setItemText(1, _translate("Users_create", "Required"))
        self.gur_Registration.setItemText(2, _translate("Users_create", "Disabled"))
        self.label_3.setText(_translate("Users_create", "On dst leg disconnection"))
        self.comboBox.setItemText(0, _translate("Users_create", "Play prompt"))
        self.comboBox.setItemText(1, _translate("Users_create", "Disconnect src"))
        self.comboBox.setItemText(2, _translate("Users_create", "Connect and play prompt"))
        self.label_39.setText(_translate("Users_create", "Login"))
        self.label_40.setText(_translate("Users_create", "Password"))
        self.label_41.setText(_translate("Users_create", "TTL"))
        self.label_24.setText(_translate("Users_create", "General options"))
        self.label_25.setText(_translate("Users_create", "NAT"))
        self.label_26.setText(_translate("Users_create", "Fax T.38"))
        self.label_27.setText(_translate("Users_create", "Convert"))
        self.label_31.setText(_translate("Users_create", "Repacketize"))
        self.label_28.setText(_translate("Users_create", "DTMF Options"))
        self.label_29.setText(_translate("Users_create", "Early Connect"))
        self.label_30.setText(_translate("Users_create", "Proxy RBT"))
        self.label_33.setText(_translate("Users_create", "SIP options"))
        self.label_34.setText(_translate("Users_create", "Ringback Tone"))
        self.label_35.setText(_translate("Users_create", "Allow Sip"))
        self.label_36.setText(_translate("Users_create", "Allow noproxy"))
        self.label.setText(_translate("Users_create", "Codex Configuration"))
        item = self.Codec_Table.horizontalHeaderItem(0)
        item.setText(_translate("Users_create", "Codec"))
        item = self.Codec_Table.horizontalHeaderItem(1)
        item.setText(_translate("Users_create", "FPP"))
        item = self.Codec_Table.horizontalHeaderItem(2)
        item.setText(_translate("Users_create", "Action"))
        self.Add_Codec_btn.setText(_translate("Users_create", "Add"))
        self.label_2.setText(_translate("Users_create", "Group"))
        self.Group_Pikcup.setText(_translate("Users_create", "Pikcup"))
        self.Group_Restricted.setText(_translate("Users_create", "Restricted"))
        self.Group_All.setText(_translate("Users_create", "All"))
        self.Group_Group_Call.setText(_translate("Users_create", "Group Call"))
        self.Group_Local_Users.setText(_translate("Users_create", "Local Users"))
        item = self.Call_Table.horizontalHeaderItem(0)
        item.setText(_translate("Users_create", "Enabled"))
        item = self.Call_Table.horizontalHeaderItem(1)
        item.setText(_translate("Users_create", "Fwd Condition"))
        item = self.Call_Table.horizontalHeaderItem(2)
        item.setText(_translate("Users_create", "Source"))
        item = self.Call_Table.horizontalHeaderItem(3)
        item.setText(_translate("Users_create", "Activity Schedule"))
        item = self.Call_Table.horizontalHeaderItem(4)
        item.setText(_translate("Users_create", "Fwd Number"))
        item = self.Call_Table.horizontalHeaderItem(5)
        item.setText(_translate("Users_create", "Action"))
        self.Add_call_table_btn.setText(_translate("Users_create", "Add"))
        self.Nazad_btn.setText(_translate("Users_create", "Назад"))
        self.Create_btn.setText(_translate("Users_create", "Создать"))

