# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Gui_for_services.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Services_forma(object):
    def setupUi(self, Services_forma):
        Services_forma.setObjectName("Services_forma")
        Services_forma.resize(646, 660)
        self.centralwidget = QtWidgets.QWidget(Services_forma)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Services_enabled_check = QtWidgets.QCheckBox(self.centralwidget)
        self.Services_enabled_check.setObjectName("Services_enabled_check")
        self.verticalLayout.addWidget(self.Services_enabled_check)
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setObjectName("label_30")
        self.verticalLayout.addWidget(self.label_30)
        self.Services_SerName = QtWidgets.QLineEdit(self.centralwidget)
        self.Services_SerName.setMinimumSize(QtCore.QSize(111, 20))
        self.Services_SerName.setMaximumSize(QtCore.QSize(111, 20))
        self.Services_SerName.setObjectName("Services_SerName")
        self.verticalLayout.addWidget(self.Services_SerName)
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setMaximumSize(QtCore.QSize(158, 16))
        self.label_31.setObjectName("label_31")
        self.verticalLayout.addWidget(self.label_31)
        self.Services_command = QtWidgets.QComboBox(self.centralwidget)
        self.Services_command.setMinimumSize(QtCore.QSize(111, 22))
        self.Services_command.setMaximumSize(QtCore.QSize(111, 22))
        self.Services_command.setObjectName("Services_command")
        self.Services_command.addItem("")
        self.Services_command.addItem("")
        self.Services_command.addItem("")
        self.Services_command.addItem("")
        self.Services_command.addItem("")
        self.Services_command.addItem("")
        self.Services_command.addItem("")
        self.Services_command.addItem("")
        self.verticalLayout.addWidget(self.Services_command)
        self.Services_forma_Table = QtWidgets.QTableWidget(self.centralwidget)
        self.Services_forma_Table.setObjectName("Services_forma_Table")
        self.Services_forma_Table.setColumnCount(6)
        self.Services_forma_Table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Services_forma_Table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Services_forma_Table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Services_forma_Table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Services_forma_Table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Services_forma_Table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Services_forma_Table.setHorizontalHeaderItem(5, item)
        self.verticalLayout.addWidget(self.Services_forma_Table)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Add_serv_table = QtWidgets.QPushButton(self.centralwidget)
        self.Add_serv_table.setObjectName("Add_serv_table")
        self.horizontalLayout.addWidget(self.Add_serv_table)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Nazad_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Nazad_btn.setMinimumSize(QtCore.QSize(81, 23))
        self.Nazad_btn.setMaximumSize(QtCore.QSize(81, 23))
        self.Nazad_btn.setObjectName("Nazad_btn")
        self.horizontalLayout_2.addWidget(self.Nazad_btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.Create_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Create_btn.setMinimumSize(QtCore.QSize(81, 23))
        self.Create_btn.setMaximumSize(QtCore.QSize(81, 23))
        self.Create_btn.setObjectName("Create_btn")
        self.horizontalLayout_2.addWidget(self.Create_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        Services_forma.setCentralWidget(self.centralwidget)

        self.retranslateUi(Services_forma)
        QtCore.QMetaObject.connectSlotsByName(Services_forma)

    def retranslateUi(self, Services_forma):
        _translate = QtCore.QCoreApplication.translate
        Services_forma.setWindowTitle(_translate("Services_forma", "MainWindow"))
        self.Services_enabled_check.setText(_translate("Services_forma", "Enabled"))
        self.label_30.setText(_translate("Services_forma", "Service name"))
        self.label_31.setText(_translate("Services_forma", "Command"))
        self.Services_command.setItemText(0, _translate("Services_forma", "Impersonate"))
        self.Services_command.setItemText(1, _translate("Services_forma", "Call Park"))
        self.Services_command.setItemText(2, _translate("Services_forma", "Fax2Email"))
        self.Services_command.setItemText(3, _translate("Services_forma", "Pick Up"))
        self.Services_command.setItemText(4, _translate("Services_forma", "Auto Redial"))
        self.Services_command.setItemText(5, _translate("Services_forma", "Voice2Email"))
        self.Services_command.setItemText(6, _translate("Services_forma", "Grup Call"))
        self.Services_command.setItemText(7, _translate("Services_forma", "DISA"))
        item = self.Services_forma_Table.horizontalHeaderItem(0)
        item.setText(_translate("Services_forma", "Enabled"))
        item = self.Services_forma_Table.horizontalHeaderItem(1)
        item.setText(_translate("Services_forma", "Fwd Condition"))
        item = self.Services_forma_Table.horizontalHeaderItem(2)
        item.setText(_translate("Services_forma", "Source"))
        item = self.Services_forma_Table.horizontalHeaderItem(3)
        item.setText(_translate("Services_forma", "Activity Schedule"))
        item = self.Services_forma_Table.horizontalHeaderItem(4)
        item.setText(_translate("Services_forma", "Fwd Number"))
        item = self.Services_forma_Table.horizontalHeaderItem(5)
        item.setText(_translate("Services_forma", "Action"))
        self.Add_serv_table.setText(_translate("Services_forma", "Add"))
        self.Nazad_btn.setText(_translate("Services_forma", "Назад"))
        self.Create_btn.setText(_translate("Services_forma", "Создать"))

