# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Gui_for_Groups.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Group_forma(object):
    def setupUi(self, Group_forma):
        Group_forma.setObjectName("Group_forma")
        Group_forma.resize(196, 222)
        self.centralwidget = QtWidgets.QWidget(Group_forma)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.G_Enabled = QtWidgets.QCheckBox(self.centralwidget)
        self.G_Enabled.setObjectName("G_Enabled")
        self.verticalLayout_2.addWidget(self.G_Enabled)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.G_Name = QtWidgets.QLineEdit(self.centralwidget)
        self.G_Name.setMaximumSize(QtCore.QSize(106, 20))
        self.G_Name.setObjectName("G_Name")
        self.horizontalLayout.addWidget(self.G_Name)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setMinimumSize(QtCore.QSize(111, 20))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.G_Transfer = QtWidgets.QCheckBox(self.centralwidget)
        self.G_Transfer.setObjectName("G_Transfer")
        self.verticalLayout_2.addWidget(self.G_Transfer)
        self.G_Forward = QtWidgets.QCheckBox(self.centralwidget)
        self.G_Forward.setObjectName("G_Forward")
        self.verticalLayout_2.addWidget(self.G_Forward)
        self.G_Conference = QtWidgets.QCheckBox(self.centralwidget)
        self.G_Conference.setObjectName("G_Conference")
        self.verticalLayout_2.addWidget(self.G_Conference)
        self.G_Call_waiting = QtWidgets.QCheckBox(self.centralwidget)
        self.G_Call_waiting.setObjectName("G_Call_waiting")
        self.verticalLayout_2.addWidget(self.G_Call_waiting)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.Nazad_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Nazad_btn.setMinimumSize(QtCore.QSize(81, 23))
        self.Nazad_btn.setMaximumSize(QtCore.QSize(81, 23))
        self.Nazad_btn.setObjectName("Nazad_btn")
        self.horizontalLayout_7.addWidget(self.Nazad_btn)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.Create_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Create_btn.setMinimumSize(QtCore.QSize(81, 23))
        self.Create_btn.setMaximumSize(QtCore.QSize(81, 23))
        self.Create_btn.setObjectName("Create_btn")
        self.horizontalLayout_7.addWidget(self.Create_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        Group_forma.setCentralWidget(self.centralwidget)

        self.retranslateUi(Group_forma)
        QtCore.QMetaObject.connectSlotsByName(Group_forma)

    def retranslateUi(self, Group_forma):
        _translate = QtCore.QCoreApplication.translate
        Group_forma.setWindowTitle(_translate("Group_forma", "MainWindow"))
        self.G_Enabled.setText(_translate("Group_forma", "Enabled"))
        self.label.setText(_translate("Group_forma", "Name"))
        self.label_2.setText(_translate("Group_forma", "Type"))
        self.comboBox.setItemText(0, _translate("Group_forma", "Access"))
        self.comboBox.setItemText(1, _translate("Group_forma", "Pick up"))
        self.G_Transfer.setText(_translate("Group_forma", "Transfer"))
        self.G_Forward.setText(_translate("Group_forma", "Forward"))
        self.G_Conference.setText(_translate("Group_forma", "Conference"))
        self.G_Call_waiting.setText(_translate("Group_forma", "Call waiting"))
        self.Nazad_btn.setText(_translate("Group_forma", "Назад"))
        self.Create_btn.setText(_translate("Group_forma", "Создать"))

